### ISSUE TITLE
PutObjectAsync: Tags with Umlauts fail the upload

### ISSUE THREAD

**Issue by simonthum** [minio/minio-dotnet#1017]
When adding a tag containing german umlauts (äöü) in the value, the upload fails.

In the response I can detect the missing etag, the response status code seems 0 in debugging.

I know the value is being validated, e.g. for an ampersand, so I'm happy to add an encoding/decoding step, but I did not find any guidance on the applicable constraints.

**Comment by klauspost** [comment]
You should be able to safely store base64 encoded data: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

**Comment by simonthum** [comment]
Thanks for letting me know, this helps a lot!

However, I think the real issue is mostly silent failure when I do not comply with this constraint. An exception or error code would be much better than a missing ETag in a response object.
