### ISSUE TITLE
Update README with steps to run examples on Linux

### ISSUE THREAD

**Issue by krisis** [minio/minio-dotnet#103]

**Comment by koolhead17** [comment]
@krisis https://github.com/minio/minio-dotnet/blob/master/README.md has steps to Run on Linux (Ubuntu), anything missing you found?

**Comment by vadmeste** [comment]
I followed the steps in the README and I found this error:
```
$ mcs /r:Minio/bin/Release/Minio.dll Minio.Examples/ListBuckets.cs
Minio.Examples/ListBuckets.cs(30,62): error CS0103: The name `ConfigurationManager' does not exist in the current context
Minio.Examples/ListBuckets.cs(31,42): error CS0103: The name `ConfigurationManager' does not exist in the current context
```

I am using Ubuntu 16.04 64bits. But not sure if I did something before that triggered this error.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by krisis** [comment]
@vadmeste I think we need to add a reference to ``System.Configuration.dll`` in ``Minio.Examples`` project.

**Comment by vadmeste** [comment]
@krisis, yes.. however I found the reference already there https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Minio.Examples.csproj#L40, so maybe it is another problem or we need to add this reference using an IDE which knows what it needs to do (actually, I am compiling from linux console), does it compile fine in your machine ?

**Comment by krisis** [comment]
@vadmeste I haven't tried it on a Linux machine.

**Comment by deekoder** [comment]
Not Applicable anymore. We cover examples in  #118 and we will support Visual Studio.
