### ISSUE TITLE
api: Implement SetBucketNotification, GetBucketNotification, DeleteBucketNotification

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-dotnet#108]

**Comment by harshavardhana** [comment]
> We need this feature, can you please provide ETA for this?
> Or can you give an approach how to get a callback that file is uploaded (webhook maybe etc...)?

If possible please use https://github.com/minio/minio-go or https://github.com/minio/minio-js - this library is going through a re-write and this feature won't be available anytime soon.

**Comment by poornas** [comment]
@deekoder, this was fixed in #136
