### ISSUE TITLE
Add tag filtering to ListObjects

### ISSUE THREAD

**Issue by jan-pokorny** [minio/minio-dotnet#1108]
Right now there is no way how to filter objects by tag when listing them.

**Proposal:**
`public ListObjectsArgs WithTags(IDictionary<string, string> tags);`
`public ListObjectsArgs WithTag(string key, string value);`

**Usage:**
```
var args = new ListObjectsArgs()
    .WithBucket(bucket)
    .WithPrefix(folder)
    .WithTag("category", "image")
    .WithRecursive(true);
```

**Comment by klauspost** [comment]
@jan-pokorny The [S3 API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestParameters) does not provide tag based listing.

**Comment by jan-pokorny** [comment]
Ah, so what are they there for, then?

**Comment by klauspost** [comment]
@jan-pokorny Ask AWS ;)
