### ISSUE TITLE
Evaluate migrating to .NET Core for all the dependencies.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-dotnet#116]
https://www.nuget.org/packages/RestSharp.NetCore/

**Comment by harshavardhana** [comment]
// cc @poornas we need to evaluate if our SDK will work with .NET Core - https://github.com/dotnet/core

**Comment by deekoder** [comment]
fix is available. Will be merged soon.

**Comment by kfuglsang** [comment]
Do you have any ETA on this?

**Comment by poornas** [comment]
There is a PR currently under review. Tentatively it will be Apr 28.

**Comment by harshavardhana** [comment]
Fixed in #124
