### ISSUE TITLE
Performance of minio / play.min.io?

### ISSUE THREAD

**Issue by mahop-net** [minio/minio-dotnet#1211]
Hello and just a question.

Is the performance of play.min.io very low compared to real production installation?

With the samples from this git project (C# .net) it takes me around 0,5 seconds to call GetObject with a file of 6,5 KB in size. 

Code is:
- Create Minio Client
- List Objects in a Bucket
- Get each Object

There are 25 Files in the bucket each with around 6,5 KB in size.

To get the list and all 25 Objects it takes 13 Seconds...??? 

(I have a DSL connection to the internet with around 200 MBit and I'm in the south of germany.)

Is this performance normal for minio?

**Comment by harshavardhana** [comment]
play.min.io is a demo VM, not meant for performance measurements.
