### ISSUE TITLE
Support for NetCore1.1

### ISSUE THREAD

**Issue by havenvo** [minio/minio-dotnet#133]
Got this error:

error: Package Minio 0.2.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Minio 0.2.1 supports: net45 (.NETFramework,Version=v4.5)

**Comment by harshavardhana** [comment]
NetCore support is only available in master branch. We haven't made a release yet.

**Comment by poornas** [comment]
@deekoder, we are just waiting for package to be published to nuget on this one.

**Comment by poornas** [comment]
Minio.Netcore 1.0.0 has been published on NuGet
