### ISSUE TITLE
Support for metadata not in .netCore nuget package

### ISSUE THREAD

**Issue by Hermain** [minio/minio-dotnet#153]
I discovered that the .netCore Nuget package contains no PutObjectAsync method with metadata in ObjectOperations.cs

To fix this issue I checked out the git repo and used the sources directly. However there the method signature is:
```
public async Task PutObjectAsync(string bucketName, string objectName, string fileName, string contentType = null, CancellationToken cancellationToken = default(CancellationToken), Dictionary<string, string> metaData = null) 
```

In the [API.md](https://github.com/minio/minio-dotnet/blob/master/Docs/API.md#putobjectasyncstring-bucketname-string-objectname-stream-data-long-size-string-contenttype) however the metaData argument comes before the CancellationToken.

**Comment by ondrejtomcik** [comment]
Same issue. Need to use metadata but nuget package is not up to date and documentation does not reflect reality. +1

**Comment by deekoder** [comment]
Will look at it soon. Thanks for filing this issue.

**Comment by Hermain** [comment]
Great that you fixed this. Will the nuget packages be updated so that the world can use these things without cloning the git repo?

**Comment by ondrejtomcik** [comment]
This issue is not solved. 

> I discovered that the .netCore Nuget package contains no PutObjectAsync method with metadata in ObjectOperations.cs

Missing nuget package with newest changes is the primary issue imho

**Comment by harshavardhana** [comment]
> This issue is not solved.

The issue is closed once the PR is merged. nuget package will soon follow.

**Comment by poornas** [comment]
@Hermain  and @ondrejtomcik , nuget package has been updated for PutObjectAsync with metadata
