### ISSUE TITLE
Support Xamarin

### ISSUE THREAD

**Issue by kvandake** [minio/minio-dotnet#158]
Do you plan to support [Xamarin](https://xamarin.com)?

**Comment by poornas** [comment]
@kvandake, minio .net SDK runs on Visual Studio for Mac. So you could pull in the nuget package into your project and check it out.

**Comment by poornas** [comment]
That's really neat @kvandake.If you plan to send a pull request,  the xamarin/Xamarin folder hierarchy will make it difficult to integrate into the code base. Does Xamarin have inbuilt tools to convert .net code to droid?

**Comment by ebozduman** [comment]
I'm moving this to `Future` milestone at least until we hear from @kvandake.

**Comment by kannappanr** [comment]
Not required right now. Will implement this if we get more support/ interest from the community.
