### ISSUE TITLE
ListBucketsAsync not word,what I can do?

### ISSUE THREAD

**Issue by billschen** [minio/minio-dotnet#159]
@koolhead17 
I use **Install-Package Minio** to install  .NET SDK like:
![del_1](https://user-images.githubusercontent.com/19528399/29020647-52de0b10-7b95-11e7-8731-6f2f604c6461.png)
Next i follow the the page [https://github.com/minio/minio-dotnet](https://github.com/minio/minio-dotnet) and create a win form to list bucket:
`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Minio;
using Minio.DataModel;
namespace HanPengWindowsForms
{
    public partial class MinioForm : Form
    {
        public const string endpoint = "play.minio.io:9000";
        public const string accessKey = "Q3AM3UQ867SPQQA43P2F";
        public const string secretKey = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG";

        private static MinioClient minio = new MinioClient(endpoint,accessKey, secretKey).WithSSL();

        public MinioForm()
        {
            InitializeComponent();
        }

        private void btnlistbucket_Click(object sender, EventArgs e)
        {
            this.btnlistbucket.Text = "loading...";
            Application.DoEvents();
            var getListBucketsTask = minio.ListBucketsAsync();
            this.lbxBucket.Items.Clear();
            foreach (Bucket bucket in getListBucketsTask.Result.Buckets)
            {
                Console.Out.WriteLine(bucket.Name + " " + bucket.CreationDateDateTime);
                this.lbxBucket.Items.Add(bucket.Name);
            }
            Console.WriteLine("complete!");
            MessageBox.Show("完成！");
            this.btnlistbucket.Text = "list bucket";
        }
    }
}
`
but when I click the button.The code block! like this
![del_2](https://user-images.githubusercontent.com/19528399/29020945-6a594fec-7b96-11e7-9795-9ad0dfba60d2.png)

**Comment by poornas** [comment]
@billschen, is it possible for you to share your csproj?

**Comment by kvandake** [comment]
please use 
```cs
    private async void btnlistbucket_Click(object sender, EventArgs e)
    {
        this.btnlistbucket.Text = "loading...";
        Application.DoEvents();
        var getListBucketsTask = await minio.ListBucketsAsync();
        this.lbxBucket.Items.Clear();
        foreach (Bucket bucket in getListBucketsTask.Buckets)
        {
            Console.Out.WriteLine(bucket.Name + " " + bucket.CreationDateDateTime);
            this.lbxBucket.Items.Add(bucket.Name);
        }
        Console.WriteLine("complete!");
        MessageBox.Show("完成！");
        this.btnlistbucket.Text = "list bucket";
    }
```

**Comment by poornas** [comment]
@billschen, did using await for the ListBucketsAsync call resolve your issue?

**Comment by billschen** [comment]
@kvandake :+1:  @poornas .Sorry for replay so late.
@kvandake's code is work!. It's my mistake. I don't no much about async method!
