### ISSUE TITLE
RestSharp.NetCore 105.2.3 dependency on System.Runtime.Serialization.Formatters

### ISSUE THREAD

**Issue by RaviSamsher** [minio/minio-dotnet#175]
I am getting an warning about restsharp.netcore...

Warning msg is **"RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved."**

![image](https://user-images.githubusercontent.com/2942630/30707031-d47a9fbc-9f17-11e7-805f-e1de9a739a84.png)

**Comment by poornas** [comment]
Thanks for raising the issue @RaviSamsher , it is safe to ignore the dependency warning for now. We will fix this package dependency with the next release of the SDK.

**Comment by deekoder** [comment]
closing this as Won't fix since the fix is outside of our codebase.

**Comment by alexeyzimarev** [comment]
Use the latest RestSharp instead.

**Comment by poornas** [comment]
Thanks @alexeyzimarev, that's great news. We will switch over.
