### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by wowi42** [minio/minio-dotnet#179]
Hi,

we've deployed a minio instance for one of our project, but we were facing some issues with the .net client:

- we've changed the name of the region in the minio server conf to abu-dhabi-1
- Signature was invalid with the .net client

I didn't find any way to modify this region in the .net constructor.

Could you please confirm what should be the default behavior?

Regards

**Comment by poornas** [comment]
@wowi42 , abu-dhabi-1 is not a valid region supported by aws s3 - you can find a list of valid endpoint regions here (http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region). If the minio server is configured to a specific region, the only time you would pass this region from the .net sdk is when you do a MakeBucketAsync call.

**Comment by poornas** [comment]
@wowi42 , did we answer your question and is there anything else we can help with? Please feel free to close this issue if it is resolved for you.

**Comment by deekoder** [comment]
closing. Please reopen if we didnt answer your wuetion @wowi42
