### ISSUE TITLE
How to get lots of objects efficiently? Like Pagination or else?

### ISSUE THREAD

**Issue by Wincy94** [minio/minio-dotnet#181]
I want to know how to get lots of objects efficiently. Because lists all objects every time and analogs paging seems a little bit slow. Do you have any other solution?

**Comment by poornas** [comment]
@Wincy94, have you tried setting the prefix on the ListObjectsAsync call? That would restrict the number of objects retrieved to the ones matching the object name prefix  - e.g. ListObjectsAsync("my-bucket","my-prefix"). 

Could you elaborate on your use case?

**Comment by Wincy94** [comment]
Thanks for your reply. Yes, I had set the prefix. But I want to get all objects with same prefix in the bucket right now. Does it have any solution like return 1000 obejects in one time and get the other objects in next time?

**Comment by harshavardhana** [comment]
> Thanks for your reply. Yes, I had set the prefix. But I want to get all objects with same prefix in the bucket right now. Does it have any solution like return 1000 obejects in one time and get the other objects in next time?

You are getting 1000 objects at one time we just add yielder to stream all the output so essentially you never have to paginate,  current implementation is an efficient implementation which allows for you to implement higher level functionality. If you need low level access you should use aws-sdk-dotnet, this SDK is not built for this purpose.

**Comment by Wincy94** [comment]
Fine, thanks for your help~
