### ISSUE TITLE
Setup interfaces for Minio Client to be testable

### ISSUE THREAD

**Issue by Disturbing** [minio/minio-dotnet#182]
Would be great for the MinioClient to be testable via interfaces :)

**Comment by harshavardhana** [comment]
Can you explain more on this a bit? Looks like the issue description is incomplete.

**Comment by Disturbing** [comment]
I can't easily mock the MinioClient for testing - have to create a wrapper
around it.  Would be great to have the classes implement an interface.

**Comment by harshavardhana** [comment]
An interface is only useful here if you wish to create many types of clients. That is out of scope for minio-dotnet IMHO.

**Comment by Disturbing** [comment]
The point is if I want to make a Mock Minio folder (locally for testing), I
have to create some sort of Interface like

class IFileStorage
void GetFile(string path);

Within that I would have an implementation of minio.

Preferably, it would be nice to have IMinioClient, mock it, and return the
files as peer Minio's functions.

It's just a bit more test friendly is all, but not a priority.

Thanks for taking the time to consider.

**Comment by Roll4D6** [comment]
Why the issue is closed? I think it makes sense to extract an interface from the MinioClient. As @Disturbing said it would make easier to mock MinioClient and easier for dependency injection
