### ISSUE TITLE
Regions (again) .netcore

### ISSUE THREAD

**Issue by thestarkey** [minio/minio-dotnet#183]
Hi, seems that all regions other than us-east-1 are not working for `PutObjectAsync,` and there is no way to set regions in any constructor or parameter.  Am I missing something?  When I try `PutObjectAsync`, I get:

`File Upload Error: Minio API responded with message=The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'`

**Comment by poornas** [comment]
@thestarkey, region can only be passed when you do a MakeBucketAsync call. PutObjectAsync will automatically detect region - what is the endpoint being passed to the MinioClient constructor?

**Comment by thestarkey** [comment]
Thanks, I'm using s3.amazonaws.com

**Comment by poornas** [comment]
@thestarkey, this is a bug in the sdk, thanks for reporting. Will be sending a fix shortly.

**Comment by thestarkey** [comment]
Awesome, thanks!!
