### ISSUE TITLE
Switch from Restsharp.Netcore to Restsharp

### ISSUE THREAD

**Issue by poornas** [minio/minio-dotnet#186]
Restsharp has now added support for .Netstandard 2.0 
(https://github.com/restsharp/RestSharp/pull/1025). Need to replace Restsharp.Netcore in favor of the official sdk.

**Comment by poornas** [comment]
closing this as it is a nice to do rather than pressing concern.

**Comment by twgraham** [comment]
Is it really a big deal to fix? I tried doing the change myself and it didn't seem to break anything (the API's seem the same). 

As a net core user, every time I build I'm reminded that `minio-dotnet` is using libraries that can't resolve their own dependencies correctly. Although it might not be the case, It makes me feel as though support for net core is a secondary priority.

```bash
/MyProject.csproj : warning NU1603: RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved. [/MyProject.csproj]
/MyProject.csproj : warning NU1603: RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved.
/MyProject.csproj : warning NU1603: RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved.
/MyProject.csproj : warning NU1603: RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved.
```

**Comment by poornas** [comment]
@twgraham, when I tried the conversion it seemed to break the signature verification. Thanks for the feedback - will revisit this as I find bandwidth.

**Comment by BlitzinBuffalo** [comment]
Is there any chance this can be looked at again?

I use the official `RestSharp` in my .Net Core 2 project, but when I try adding `Minio.NetCore`, I am faced with a number of `ambiguous reference` errors.

**Comment by poornas** [comment]
@BlitzinBuffalo , PR https://github.com/minio/minio-dotnet/pull/212 is adding official Restsharp support.
