### ISSUE TITLE
Add setting response Content-Disposition header for PresignedGetObject

### ISSUE THREAD

**Issue by xmichaelx** [minio/minio-dotnet#187]
In JS minio client we can set response headers like Content-Disposition while getting presigned get object, could we have the same functionality in dotnet client?

**Comment by poornas** [comment]
@xmichaelx, this is already supported - you need to pass request parameters in a dictionary. 
https://github.com/minio/minio-dotnet/blob/master/Docs/API.md#presignedGetObject

**Comment by xmichaelx** [comment]
Thanks! Could you update nuget package Minio then? Version 1.0.2 does not have this additional argument for PresignedGetObjectAsync method.

**Comment by harshavardhana** [comment]
> Thanks! Could you update nuget package Minio then? Version 1.0.2 does not have this additional argument for PresignedGetObjectAsync method.

We will update it soon. @xmichaelx

**Comment by poornas** [comment]
@xmichaelx, package has been updated.

**Comment by xmichaelx** [comment]
You've  updated existing 1.0.2 package or bumped the version to 1.0.3?

**Comment by harshavardhana** [comment]
> You've updated existing 1.0.2 package or bumped the version to 1.0.3?

1.0.3 we will be making 1.0.4 by next week as well.
