### ISSUE TITLE
Functional test: Do not display fields that has empty strings in the JSON log

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-dotnet#196]
Fields with empty strings should not be displayed.
```
{"name":"Minio.Net","function":"BucketExists_Test","duration":817,"status":"PASS","alert":"","message":"","error":""}

```
In the example given above, alert, message and error are all empty and should not be displayed.

**Comment by poornas** [comment]
@nitisht , will reassign this to myself as this is a one line change, and belongs with other fixes to logging.
