### ISSUE TITLE
Functional test: value of name field should be lower case

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-dotnet#197]
Value of the `name` field should be lower case.
`{"name":"Minio.Net","function":"BucketExists_Test","duration":817,"status":"PASS","alert":"","message":"","error":""}`

Here `Minio.Net` should be  `minio-.net` to be consistent with other SDKs

**Comment by poornas** [comment]
@kannappanr, this is a small change that is part of the logging fixes. will fix it as part of #194-#196. Reassigning to myself.
