### ISSUE TITLE
Assembly not found: Minio.XmlSerializers

### ISSUE THREAD

**Issue by tobmatth** [minio/minio-dotnet#207]
I'm facing a `FileNotFoundException` for `Minio.XmlSerializers, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null` when running the following code snippet:

    IObservable<Item> observable = minioClient.ListObjectsAsync(this.minioBucket, null, true);
    IDisposable subscription = observable.Subscribe(
      item => Debug.WriteLine(item.Key));
    observable.Wait<Item>();

My server is the latest version running on Windows, .NET SDK is version 1.0.6. There seems to be something wrong with my project setup, but i'm a bit lost on how to tackle this...

**Comment by poornas** [comment]
@tobmatth, are you using VS 2017 or VS 2015? SDK works only on VS 2017. You might want to run the example project ```https://github.com/minio/minio-dotnet/tree/master/Minio.Examples/Minio.Client.Examples.Net452``` and see if the ListObjectsAsync method throws up an error.

**Comment by tobmatth** [comment]
I'm using VS 2015. Thanks for the hint, will try VS 2017 tomorrow...

**Comment by tobmatth** [comment]
Works in Visual Studio 2017, thanks...
