### ISSUE TITLE
BucketExistsAsync fails silently in a VS 2017 unit test debug session

### ISSUE THREAD

**Issue by MedAnd** [minio/minio-dotnet#209]
The following call fails silently in a VS 2017 unit test debug session:

`bool found = await _minioClient.BucketExistsAsync(bucketName);`

debugging the Minio .Net client code it seems to be the following line:

![image](https://user-images.githubusercontent.com/13365135/34862135-c92d9026-f7bc-11e7-93a4-666a96f116ec.png)

**Comment by kannappanr** [comment]
@MedAnd Does it work in `release` mode? When you say `fail silently`, can you explain that behavior in more detail?

**Comment by MedAnd** [comment]
Will have to get back to you about release mode but I’m checking if bucket exists else create bucket in a unit test... there are no exceptions and the tests passes yet no bucket or file are created...

**Comment by kannappanr** [comment]
Is it possible to paste the source code here? Also, what is the unit test trying to do?

**Comment by poornas** [comment]
@MedAnd, the line you highlighted just makes a GET location call so that we can cache the region your bucket is on. you might want to break on ParseError() method that parses response status for the HEAD call (i.e. after the location call returns) - what is the response status and error code you receive? It is possible there might be a bug here.

**Comment by poornas** [comment]
@MedAnd , are you still encountering an error?

**Comment by MedAnd** [comment]
@poornas, having re-written my unit tests now to use latest .Net Core I am not able to repro... 

The original unit tests were for .Net46, in addition I also force downgraded JSON.Net to be < 10... which could be the root cause but still requires further testing... I needed to downgrade due to clashes with other open source libraries I already use such as Elasticsearch NEST. 

PS. I can close and re-open should there be a need?

**Comment by poornas** [comment]
@MedAnd, I am closing this for now. Feel free to reopen if you see the issue again.
