### ISSUE TITLE
ExecuteTaskAsync

### ISSUE THREAD

**Issue by jerauskin** [minio/minio-dotnet#210]
Hello, I'm using your library in a Winforms project and ExecuteTaskAsync function of MinioClient.cs hangs executing ListBucketsAsync() function. SimpleTest.cs runs OK with same parameters.

Thanks for your library

**Comment by poornas** [comment]
which version of .NET are you using @jerauskin? Can you share the snippet of relevant code where you are calling ListBucketsAsync?

**Comment by jerauskin** [comment]
Hello,

 

I'm using .NET 4.5.2 and I think de problem is In RestSharp library. The code is very simple:

 

using System;

using System.Net;

using System.Threading.Tasks;

using System.Windows.Forms;

using Minio;

using Minio.DataModel;

 

namespace Mantenimiento_Arq_Backup

{

    public partial class frmPrincipal : Form

    {

 

        public frmPrincipal()

        {

            InitializeComponent();

        }

 

        private async void button1_Click(object sender, EventArgs e)

        {

            conectarSpaces();

        }

 

        private void conectarSpaces()

        {

            var minio = new MinioClient(ConfigurationManager.AppSettings["Endpoint"],

                ConfigurationManager.AppSettings["AccessKey"],

                ConfigurationManager.AppSettings["SecretKey"]).WithSSL();

            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

                                                  | SecurityProtocolType.Tls11

                                                  | SecurityProtocolType.Tls12;

            // Create an async task for listing buckets.

            var getListBucketsTask = minio.ListBucketsAsync();

            try

            {

                Task.WaitAll(getListBucketsTask); // block while the task completes

            }

            catch (AggregateException aggEx)

            {

                MessageBox.Show(aggEx.Message);

            }

            var lista = getListBucketsTask.Result;

            foreach (Bucket bucket in lista.Buckets)

            {

                var bucketExistTask = minio.BucketExistsAsync(bucket.Name);

                Task.WaitAll(bucketExistTask);

                var existe = bucketExistTask.Result;

            }

        }

 

    }

}

 

Thanks for your quick answer.

 

Best regards

 

De: poornas [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de enero de 2018 20:39
Para: minio/minio-dotnet <minio-dotnet@noreply.github.com>
CC: jerauskin <jerauskin@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [minio/minio-dotnet] ExecuteTaskAsync (#210)

 

which version of .NET are you using @jerauskin <https://github.com/jerauskin> ? Can you share the snippet of relevant code where you are calling ListBucketsAsync?

**Comment by jerauskin** [comment]
Hello,

 

I found the solution. I follow the instructions of this page: 

 

http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

 

And I change this code:

 

            var getListBucketsTask = minio.ListBucketsAsync();

            try

            {

                Task.WaitAll(getListBucketsTask); // block while the task completes

            }

            catch (AggregateException aggEx)

            {

                aggEx.Handle(HandleBatchExceptions);

            }

            var list = getListBucketsTask.Result;

 

 

For this one:

 

                var getListBucketsTask = await minio.ListBucketsAsync();

                var lista = getListBucketsTask;

 

And no more deadlocks.

 

Thanks for your great library and best regards.

 

De: poornas [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de enero de 2018 20:39
Para: minio/minio-dotnet <minio-dotnet@noreply.github.com>
CC: jerauskin <jerauskin@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [minio/minio-dotnet] ExecuteTaskAsync (#210)

 

which version of .NET are you using @jerauskin <https://github.com/jerauskin> ? Can you share the snippet of relevant code where you are calling ListBucketsAsync?

**Comment by poornas** [comment]
that's good @jerauskin
