### ISSUE TITLE
Accessing LastModifiedDateTime when using recursive is false throws Exception

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio-dotnet#224]
Hi,

When I loop over objects in minio using recursive=false and then accessing the LastModifiedDateTime property it throws an exception:

"ArgumentNullException: String reference not set to an instance of a String.Parameter name: s"

The reason seems to be the DateTime.Parse here:
https://github.com/minio/minio-dotnet/blob/1fd303c25a238d7aa08d72d4b50b549ceb9dac68/Minio/DataModel/Item.cs#L54

In the case of a "folder" LastModified is Null and DateTime.Parse fails.

I'd prefer this to return either null aswell (maybe make the DateTime a nullable) or for example DateTime.Min as otherwise the whole Observable seems to fail.

**Comment by WolfspiritM** [comment]
@poornas I was running minio inside a docker container. It's not an empty folder.
I created files under the key test/folder/file

Then I do GetObjectAsync with prefix "test/" and LastModified is null.

Here is my test code:
https://gist.github.com/WolfspiritM/7cee41b0ceae6d5a9fecaa6192e7fe27
(using Minio.NetCore)


It Outputs:
```
c.LastModified:
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.DateTime.Parse(String s)
   at Minio.DataModel.Item.get_LastModifiedDateTime() in /q/.q/sources/minio-dotnet/Minio/DataModel/Item.cs:line 54
   at miniotest.Program.<>c.<Run>b__1_0(Item c) in C:\Users\Wolfspirit\Documents\Projects\miniotest\Program.cs:line 32
```

**Comment by poornas** [comment]
@WolfspiritM , thanks - I was able to repro the issue, will send a fix shortly.
