### ISSUE TITLE
Download large files

### ISSUE THREAD

**Issue by dmpriso** [minio/minio-dotnet#225]
When using ```async``` semantics to get a large file, the whole file must be read into RAM, also blocking a thread. This is especially an issue in a server environment.

One might expect the following to work:
```
    IO::Stream stream;
	
    await m_client.GetObjectAsync(this.m_bucket,
                path,
                s => stream = s,
                cancellationToken);
	
    await data = stream.read() ...

```

However that fails because the stream "s" must be consumed inside the stream callback. This is because RestSharp closes the request immediately after calling the callback.
There is actually a closed issue over there on that:

https://github.com/restsharp/RestSharp/issues/539

While that may be an "edge case" for RestSharp, it is clearly an issue here where we could easily be dealing with large files. The only way to read a file is as in the example:

```
    IO::MemoryStream stream;
	
    await m_client.GetObjectAsync(this.m_bucket,
                path,
                s => s.CopyTo(stream),
                cancellationToken);
	
    data = stream.read() ...

```

However, that uses much RAM and blocks a thread in the threadpool when being run in a service.

**Comment by poornas** [comment]
thanks @twgraham, that's worth exploring

**Comment by deekoder** [comment]
We will take a look into this in the next milestone. @twgraham we are wrapping up our current priorities first. I will close it and park it in future milestone. We will reactivate from future milestone after we are done with current priorities.

**Comment by gerwim** [comment]
+1. Yes please, downloading large files is currently not possible (atleast 1GB+) because of this. The official S3 API supports this (as you can wrap the GetObjectAsync inside an using, e.g. https://docs.aws.amazon.com/AmazonS3/latest/dev/RetrievingObjectUsingNetSDK.html)

**Comment by ptr1120** [comment]
Please consider to reopen this issue, because for the minio main use case it seems to have a high priority to support downloading files async and be able to stream files without loading the whole content into memory. A closed issue does not support fixing this in near future.

**Comment by KyleGobel** [comment]
Is this still planned?  I thought it was strange when I first saw to access the stream you had to provide a callback, i guess that's just because of RestSharp?

IMO this makes the client library pretty limiting.

**Comment by autiarii** [comment]
Still a problem, one have to state it is clearly NOT production ready when it comes to larger files paired with dotnet client.

**Comment by toxsedyshev** [comment]
Why this issue is closed?

**Comment by toxsedyshev** [comment]
My async wrapper to get rid of callbacks: https://stackoverflow.com/a/77158662/3334359

**Comment by cvetomir-todorov** [comment]
This issue should not be closed, downloading large files without loading them entirely into memory is a critical functionality.

Returning a `Stream` object referring to the file contents in MinIO is required in order to make it work with ASP.NET which allows for downloading files via `return File(stream, mimeType);` in the controller.

Giving access to the `Stream` via a callback is extremely weird and unusable. You guys should look at it, if you want to be taken seriously.

**Comment by Ali-Masaeli** [comment]
Program.cs:

var builder = WebApplication.CreateBuilder(args);

var minioClient = new MinioClient()
    .WithEndpoint(new Uri("http://127.0.0.1:9000"))
    .WithCredentials("admin", "12345678")
    .WithSSL(false)
    .Build();

Controller:

  [HttpGet("download/{objectName}")]
  public async Task<IActionResult> Download(string objectName)
  {
      var exists = await _minio.BucketExistsAsync(new BucketExistsArgs().WithBucket(_bucketName));
      if (!exists) return NotFound($"Bucket '{_bucketName}' not found.");

      Response.ContentType = "application/octet-stream";
      Response.Headers.Add("Content-Disposition", $"attachment; filename={objectName}");

      await _minio.GetObjectAsync(
          new GetObjectArgs()
              .WithBucket(_bucketName)
              .WithObject(objectName)
              .WithCallbackStream(async (stream, ct) =>
              {
                  var buffer = new byte[81920];
                  int bytesRead;
                  while (!HttpContext.RequestAborted.IsCancellationRequested &&
                         (bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length, ct)) > 0)
                  {
                      await Response.Body.WriteAsync(buffer, 0, bytesRead, ct);
                      await Response.Body.FlushAsync(ct);
                  }
              })
      );
      return new EmptyResult();
  }
