### ISSUE TITLE
4.5.2 support dropped?

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio-dotnet#235]
Hi,

I've an older project which still targets .NET 4.5.2 but it seems like 2.0 doesn't target 4.5.2 anymore.
Is that a mistake or is the Readme just not updated yet and I have to upgrade to .NET 4.6?

https://github.com/minio/minio-dotnet/blob/master/Minio/Minio.csproj#L5

**Comment by poornas** [comment]
@WolfspiritM, the Readme has to be updated - we simplified the build system and moved to official version of Restsharp client for Minio, because of multiple incompatibilites between packages, we had to move the minimum version supported for .NET framework to .net4.6

**Comment by kannappanr** [comment]
@WolfspiritM Closing this issue as answered.
