### ISSUE TITLE
Invalid endpoint

### ISSUE THREAD

**Issue by DeepSnowNeeL** [minio/minio-dotnet#238]
Hello i'm trying to use minio on docker containers, and I usually use docker names as hostnames since it resolves correctly with the docker DNS system.

But I can't because I got this exception :
`Minio.Exceptions.InvalidEndpointException: 'Minio API responded with message=Endpoint: minio_recette does not follow ip address or domain name standards.'`

I use both the java & c# api for minio, and solved my problem on the java side by using http://minio_recette:9000 as my endpoint, but the c# doesn't allow for "/" in the endpoint.

Could you please support simple names, for docker containers ? Thanks

I'm still trying to find a way around this...

**Comment by poornas** [comment]
@DeepSnowNeeL, init the c# client like this and it should work. 
```
private static MinioClient minio = new MinioClient("minio_recette:9000",
                "accesskey",
                "secretkey"
                );
```

**Comment by DeepSnowNeeL** [comment]
Great :) 
Please make it work for the java API as well. (and others ?)

Btw, It works when I specify the IP directly so I'll use that for now

**Comment by WolfspiritM** [comment]
This is causing us issues aswell.
With docker this is definitely needed as docker distincts stacks based on stackname_servicename.

**Comment by leeroya** [comment]
For the dotnet project, I am using I used only the IP: Port configuration i.e. "127.0.0.1:9000".

**Comment by deekoder** [comment]
Will address in the future. As mentioned earlier, we will reactivate this into current milestone when we are done with current priorities.

**Comment by mangrer** [comment]
I see the issue was reported closed? Have there been any updates or workaround figured for this issue?
