### ISSUE TITLE
Support server-side encryption

### ISSUE THREAD

**Issue by Brunni** [minio/minio-dotnet#251]
Support server-side encryption feature of minio:
Needed headers:
- X-Amz-Server-Side-Encryption-Customer-Algorithm
- X-Amz-Server-Side-Encryption-Customer-Key
- X-Amz-Server-Side-Encryption-Customer-Key-MD5

see https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-server-side-encryption-with-aws-cli.md

**Comment by kannappanr** [comment]
@Brunni  Thanks for filing this issue. We will try to add this in the near future.
