### ISSUE TITLE
When using PutObjectAsync command bucket update time is being continuously updated after transfer has completed.

### ISSUE THREAD

**Issue by RichardMendelsohn** [minio/minio-dotnet#254]
Steps:
Copy File To bucket/foo using PutObjectAsync
Observe call has finished, and mc ls -I shows no incomplete jobs on bucket
Observe update time for bucket is still being constantly set to the current time

**Comment by kannappanr** [comment]
@RichardMendelsohn Thanks for filing this issue. We will take a look at this issue and get back to you.

**Comment by krisis** [comment]
@RichardMendelsohn I was not able to recreate the issue you describe above using `Minio 2.0.6` version of the package. I wrote a standalone C# console application that uploads a file present on my (Linux) system to a local Minio object server using `PutObjectAsync` SDK method. It works as expected.

To further analyse the issue you are facing, it would be helpful if you can,
- attach a small program that recreates the problem you observe
- include the version of Minio package you are using in your application

**Comment by krisis** [comment]
@RichardMendelsohn do you still see the issue in your setup? Could you provide a small program that would recreate the issue?

**Comment by deekoder** [comment]
@RichardMendelsohn  closing this as not reproducible. Please reactivate it and help us repro. Feel free to reactivate this bug anytime.
