### ISSUE TITLE
C# SDK: How to determine if GetObjectAsync succeeded?

### ISSUE THREAD

**Issue by petertiedemann** [minio/minio-dotnet#261]
When accessing an object with a key that does not exist, the stream provided by `GetObjectAsync` contains an XML error and does not throw and error when read, How should a caller avoid returning this XML error string in place of an actual string? I realize it is possible to call StatObjectAsync first, but that raises concerns about what happens if stat is called first, then before getobject a remove call is made. 

## Expected Behavior
I would expect an exception from GetObjectAsync if the object could not be retrieved.

## Current Behavior
The stream contains an XML string:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/storagetest.f7f3da7a3a0b4ff299794b47161dccf6/Key Not Found</Resource><RequestId>15704FE60F942D64</RequestId><HostId>3L137</HostId></Error>
```

## Possible Solution
* Provide a separate callback for the missing object scenario
* Provide a null stream
* Throw an exception

## Steps to Reproduce (for bugs)
Call GetObjectAsync and provide a non-existing object key.

## Context
I am concerned about concurrency problems with remove operations.

## Your Environment
* Version used (`minio version`): 2018-12-13T02:04:19Z
* Environment name and version (e.g. nginx 1.9.1): n/a
* Server type and version: n/a
* Operating System and version (`uname -a`): Windows 10
* Link to your project: n/a

**Comment by nitisht** [comment]
fixed by #260
