### ISSUE TITLE
Example to enumerate Bucket does not work with DotNet core 2

### ISSUE THREAD

**Issue by tburnett80** [minio/minio-dotnet#263]
Using Minio 2.0.7  and trying to enumerate the contents of a bucket using an observable never returns or triggers next()

I can list buckets but not their contents. 

Following the example, returns nothing.
```
var items = new List<string>();
if (await _client.BucketExistsAsync(bucketName))
{
    IObservable<Item> observable = _client.ListObjectsAsync(bucketName);
    IDisposable subscription = observable.Subscribe(
        item => items.Add($"Object: {item.Key}"),
        ex => items.Add($"OnError: {ex}"),
        () => items.Add("Listed all objects in bucket " + bucketName + "\n"));

    var tmp = items.ToList();
}
```

Only returns the first item.
```
var items = await _client.ListObjectsAsync(bucketName);
```

I would imagine there is an easier way to enumerate the contents of a bucket, or am I missing something?

**Comment by tburnett80** [comment]
I found what was missing from the example.

The observable should be awaited, otherwise it never completes.
After awaiting it consistently returns all the objects in the given bucket as expected.

```
public async Task<IEnumerable<string>> EnumerateBucket(string bucket)
{
    if (!await _client.BucketExistsAsync(bucket))
        return new string[0];

    var blobNames = new List<string>();
    var observable = _client.ListObjectsAsync(bucket);
    using (observable.Subscribe(item => blobNames.Add(item.Key)))
    {
        await observable;
        return blobNames.ToList();
    }
}
```

**Comment by PHWilliams** [comment]
Thanks bro this is really helpful. I've been searching for help on this  ListObjectsAsync method for days now.
