### ISSUE TITLE
Better support for non Amazon services

### ISSUE THREAD

**Issue by AdmirR** [minio/minio-dotnet#264]
Hello,

I initialized a Minio client with all four constructor parameters ("endpoint", "accessKey", "secretKey" and "region") provided, tried doing a request and got an unauthorized exception, the authorization header was invalid.

When I looked at the request it was making I noticed that it added the "us-east-1" region in the authorization header, even though I had specified a different region.

The reason it was doing this was because the "V4Authenticator" only resolved the region from the provided enpoint with an amazon.com specific regex (my enpoint is not an amazon.com endpoint). (See the V4Authenticator.getRegion function.)

It's a simple fix to let the V4Authenticator receive the region in it's constructor (which seems logical to me), but then again, I have spent about 15 minutes in the code.

Feedback appreciated.

--

Oh and Merry Christmas everyone :)

**Comment by AdmirR** [comment]
I noticed that you guys added a constructor overload for the V4Authenticator, but forgot to actually make use of that constructor in the MinioClient.CreateRequest function (line nr. 160).

**Comment by krisis** [comment]
@AdmirR, sorry for missing that out. I will add that in a separate PR. Thanks for catching it.
