### ISSUE TITLE
Minio Client SDK nugets Minio.Net and Minio.NetCore

### ISSUE THREAD

**Issue by MontyGvMC** [minio/minio-dotnet#272]
I have a question about the two existing .NET Client SDK packages/nugets:

- Minio
- Minio.NetCore

The [official download site](https://minio.io/downloads.html) shows both as available but on the nugets site [Minio nuget](https://www.nuget.org/packages/Minio/) has reached version 3 and was last updated yesterday whereas [Minio.NetCore nuget](https://www.nuget.org/packages/Minio.NetCore/) was last updated 9 months ago and remains at version 1.1.1.

This raised a discussion if Minio.NetCore nuget is "officially" deprecated and if we should only use Minio nuget for our .NETCore (2.*) projects. 

Is it?
Should we?

**Comment by poornas** [comment]
@MontyGvMC , Minio.NetCore is deprecated - Minio nuget can be used for both .NET Core and .NET framework projects

**Comment by kannappanr** [comment]
@MontyGvMC Closing this issue as answered. Please feel free to reach out to us on slack at https://minio.slack.com

**Comment by Etrimus** [comment]
Maybe it is need to mark [Minio.NetCore nuget](https://www.nuget.org/packages/Minio.NetCore) as deprecated - put this info in Nuget package description?...

**Comment by poornas** [comment]
Sure, we will do so @Etrimus
