### ISSUE TITLE
Timeouts and cancellation on Async

### ISSUE THREAD

**Issue by LordMike** [minio/minio-dotnet#279]
Hello,

I was reading through Minios code and I found this case, where I believe CancellationTokens are not applied correctly. In the code below, the provided CancellationToken is not sent to RestSharp, but only checked once (let's ignore the `StatObject` call for now), after the request has been started, but before the request is being awaited. 

It's my impression that the common case for a cancellation is that it will happen _after_ the request has been started (since this part takes milliseconds), and thereby the check in Minio will already have passed by the time the Cancellation is fired.

https://github.com/minio/minio-dotnet/blob/3e89239478bf8b693c22d9219246244af8ccc4b0/Minio/MinioClient.cs#L340-L360

Minio should pass on the CancellationToken to RestSharp, so that they can apply it in their respective read/write loops, ensuring that a blocking read (network dropped) or slow download (downloading very large files f.ex.) will never run for more than a given amount of time.

Also. Isn't there another flaw here as well? If I start a `GetObjectAsync` with a CancellationToken that almost immediately cancels (imagine I hit the `ThrowIfCancellationRequested` on line 355), won't the request continue - keep uploading or downloading or whatever it does?

**Comment by kannappanr** [comment]
@LordMike Thanks for your suggestions. We will take a look at them.

**Comment by poornas** [comment]
@LordMike, thanks for bringing this up - cancellationtoken should be passed down to Restsharp. ExecuteTaskAsync api allows passing down context

**Comment by kannappanr** [comment]
@LordMike Can you please review PR #283?

**Comment by LordMike** [comment]
@kannappanr it _should_ work. I haven't tested it as there hasn't been a release with this in it :).

**Comment by kannappanr** [comment]
Will try to make a release today.
