### ISSUE TITLE
AWS SDK vs MINIO Client SDK

### ISSUE THREAD

**Issue by Wahid101** [minio/minio-dotnet#281]
Wasn't sure where was the best place to ask so I figured Id ask here. Is there any pro/cons to using minio-dotnet vs aws sdk or is it mostly personal preference since are they designed to work interchangeably?

**Comment by poornas** [comment]
minio-dotnet implements S3 API and can work with any S3 compatible object store. There are a few differences that you might want to evaluate such as :
- Size of the nuget package - are you interested in S3 API only? AWS SDK includes APIs across their suite of products.
- Abstraction - minio-dotnet abstracts APIs such as multipart upload from the user, if you have a need for low level APIs then AWS SDK might be considered. 

You might also want to check out our SDK documentation at https://docs.minio.io or join us on slack at  https://minio.slack.com to get in touch with other questions you might have

**Comment by kannappanr** [comment]
@Wahid101 Closing this issue. Please feel to reach out to us if you have any other questions.
