### ISSUE TITLE
Support temporary credentials and X-Amz-Security-Token

### ISSUE THREAD

**Issue by antonchaika** [minio/minio-dotnet#285]
Hi, 

I'm trying to use minio on windows servers. I've downloaded .NET SDK and found that there is no support of temporary credentials. I use [client grants](https://github.com/minio/minio/blob/master/docs/sts/client-grants.md) endpoint to retrieve temporary credentials with my signed JWT token from Identity Server 3 (supports OAuth2 and OIDC). But when I'm trying to pass temp `accessKey` and `secretKey` into `MinioClient` class and get some file or information about bucket there are an error message from minio server:

> MinioException: Minio API responded with message=The security token included in the request is invalid

I can't use X-Amz-Security-Token query string and value of my session token because AWS signature is not valid for such request.

Do you have any planes or dates when you implement (or not?) this feature in upcoming release?
What can I use right now for such case?

Thanks

**Comment by harshavardhana** [comment]
@poornas this requires you to implement credentials handling like minio-go

**Comment by antonchaika** [comment]
@harshavardhana, @poornas can I use AWS S3 .Net SDK for this case with Minio server?

**Comment by poornas** [comment]
@antonchaika, yes you could use AWS S3 .Net SDK  to connect to minio server with temp. credentials. We are working on adding support for temp. credentials to minio .NET sdk

**Comment by antonchaika** [comment]
> @antonchaika, yes you could use AWS S3 .Net SDK to connect to minio server with temp. credentials.

Can you provide some sample code for `AmazonSecurityTokenServiceClient` usage with Minio server?

**Comment by poornas** [comment]
@antonchaika,  the credentials need to fetched from STS as in this  example(https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html) . The S3Config to connect to minio server can be seen in minio docs [here](https://docs.minio.io/docs/how-to-use-aws-sdk-for-net-with-minio-server.html)
