### ISSUE TITLE
Thrown exception types

### ISSUE THREAD

**Issue by MontyGvMC** [minio/minio-dotnet#288]
Working with the Minio .NET (3.0.2) I am running into a scenario where I have to react differently on different error cases (in relation with Minio).

I see that Minio.Exceptions holds a bunch of different exceptions. Unfortunatly it seems to be hard to distinguish between different error source when the exceptions are thrown.

I am running a background service receiving messages which start actions on the Minio (e.g. delete files). If an error occurs I have to decide if I requeue the message (for trying later) or drop it (to avoid messages that can't be handled in the future).

I tried something simple like:

```
  try
  {
    await minio.RemoveObjectAsync(bucket, key);
  }
  catch (ConnectionException ce)
  {
     // log temporary error
     // requeue message 
  }
  catch (MinioException e)
  {
    // log permantent error
    // drop message 
  }
```

Unfortunatly it will always be a MinioException (invalid XML repsonse) and never be a ConnectionException.

How to reproduce:

1.  write a simple command line app using the code given above
2.  ensure it will delete existing files on the first run (to ensure config is valid)
3.  set a break point to await minio.RemoveObject....
4.  reach the break point
5.  plug out the LAN cable
6.  see which exception is returned

Is there currently (with 3.0.2+) a way to distinguish between connection problems (accross all operations of minio client) and other problems?

Wouldn't throwing the different types of exceptions (not only MinioException) allow developers to differentiate by catching each exception class seperatly or handle all errors at once by catching the MinioException base type?

**Comment by poornas** [comment]
can you rerun your service with trace by setting minioclient.SetTraceOn() and post the response received for minio.RemoveObject...

**Comment by MontyGvMC** [comment]
Sure, here it is

```
Full URL of Request http://host/bucketname/subpath/guid-filename.jpg
Request completed in 46,8 ms
- - - - - - - - - - BEGIN REQUEST - - - - - - - - - -
DELETE http://host/bucketname/subpath/guid-filename.jpg
Host: host:80
X-amz-content-sha256: e3b0c44298fc1c149afbf4c89996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20190307T081025Z
Authorization: AWS4-HMAC-SHA256 Credential=intentionally-removed/20190307/us-east-1/s3/aws4_request,
SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7f52ff14756c ...and more...
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml

- - - - - - - - - - END REQUEST - - - - - - - - - -
- - - - - - - - - - BEGIN RESPONSE - - - - - - - - - -
HTTP/1.1 0 0

Der angegebene Host ist unbekannt Der angegebene Host ist unbekannt
- - - - - - - - - - END RESPONSE - - - - - - - - - -
```

The last message in english means (twice): The given host is unknown. Of course because I have plugged out the LAN cable.

A suggestion for further improvements: mind using a logger to write traces instead (as it seems) writing directly into the console. This would allow us to copy paste from the log outputs. Had to type this from the screen since (for some reason) I was unable to copy from the console output.

**Comment by poornas** [comment]
@MontyGvMC, as you can see from the trace, the HTTP response did not come with any headers or statu code - just the error message of "The given host is unknown". The sdk tries as much as possible to return a meaningful exception type, and in the event of failure to do so -wraps it into a MinioException class, which is the best we can do. In the situation as above, your application can use the ErrorResponse accessor  in MinioException if needed for the original error/further handling

**Comment by MontyGvMC** [comment]
I fully understand that a partial/broken response is treated correctly since a partial response is still a response.

I am just wondering (since I haven't checked the minio .net code) where the partial response comes from? When the server is not connected. Just curious.

**Comment by poornas** [comment]
the httpclient would have tried to resolve the endpoint address and dns lookup would have failed. Hence the partial response when you unplugged the LAN cable.

**Comment by kannappanr** [comment]
@MontyGvMC Marking this issue as answered and closing this issue. Please feel free to reopen the issue if you feel otherwise.
