### ISSUE TITLE
Setting X-Amz-Date on presigned url generation

### ISSUE THREAD

**Issue by MontyGvMC** [minio/minio-dotnet#289]
I am comming from this [StackOverflow question](https://stackoverflow.com/questions/54710199/usage-of-presigned-urls-in-a-e-g-angular-spa-blows-up-browser-cache) where I was recommended to open a new feature request on this topic.

As far as I understood the answers: setting X-Amz-Date (which seems to be available in minio.js but not in .NET client) could fix a problem with browsers caching (or actually not caching) the generated presigned urls.

Currently I am using minio to generate a presigned url like:

`minio.PresignedPutObjectAsync(bucketName, key, ttl);`

This results in a fresh presigned url with a new `X-Amz-Date=20190306T073831Z&X-Amz-Expires=28800`

Those generated urls are returned to a website repeatedly (e.g. via polling). The website then uses the presigned urls to display an image. This results in an exploding browser cache since the url changes each time and the browser treats them as different image.

As far as I understood the SO answer allowing to set the X-Amz-Date developers could use a fixed date with a fixed expiration to keep the urls the same (e.g. date-of-today-midnight + an expiration of 36 hours). I hope I understood it correct but I am no sure.

Is it possible to add the functionality of setting X-Amz-Date to the minio .NET client?

Currently I am beating this problem with a centralized cache for generated urls to make it possible to keep them the same accross a defined period of time. But I think there could be more simple solution. Because since caching the urls [stranger minio problems occur](https://stackoverflow.com/questions/55018716/how-to-find-the-source-for-the-signaturedoesnotmatch-error-on-minio).

**Comment by poornas** [comment]
@MontyGvMC, expiry date can be explicitly set if you are using the [PresignedPostPolicy API]((https://docs.minio.io/docs/dotnet-client-api-reference.html#presignedPostPolicy) call. You might want to use that instead of PresignedPutObjectAsync

**Comment by harshavardhana** [comment]
We can take the date parameter in presigned put object as well minio-go already does this.

**Comment by poornas** [comment]
yes,we can add request parameters to the api signature

**Comment by poornas** [comment]
> We can take the date parameter in presigned put object as well minio-go already does this.
PresignedHeadObject and PresignedGetObject take query parameters, not PresignedPutObject in minio-go

**Comment by MontyGvMC** [comment]
@poornas Thanks for the hint. It's just that the upload urls aren't cached by the browsers anyway. So the only interesting thing (for me) would be able to set them in the get urls.

**Comment by poornas** [comment]
@MontyGvMC, that's correct - the PresignedGetObjectAsync now allows you to pass a request date so the presigned get url can be unique for the object if your application uses the same request date. The next nuget package version should have this fix that just got merged.

**Comment by kannappanr** [comment]
PR #290 closes this issue
