### ISSUE TITLE
Problem with restsharp.dll dependency

### ISSUE THREAD

**Issue by banitt** [minio/minio-dotnet#296]
When using version 1.1.1 it says, that it requires RestSharp >= 105.2.3, but it doesn't work with newest version like 106.3.1.

**Comment by kannappanr** [comment]
@banitt Can you upgrade to the latest version of the dotnet SDK?

**Comment by banitt** [comment]
I can't since I am forced to use .Net Framework 4.5.2.

**Comment by msgpacket** [comment]
I have the same problem with my .NET 4.7.2 desktop app.  Using RestSharp 106.6.9 (latest stable), calling something like in the sample:

`await m_Client.MakeBucketAsync("newBucket");`

throws "Method not found: 'Void RestSharp.RestRequest.set_XmlSerializer(RestSharp.Serializers.ISerializer)'."

**Comment by pat-clevest** [comment]
It's a result of this commit on RestSharp that changed the data type of the "Serializer" property:
https://github.com/restsharp/RestSharp/commit/a8946d126211eb67bc1902dfb819c54d055c03e5

**Comment by poornas** [comment]
this is fixed
