### ISSUE TITLE
Disable duplicate nuget package

### ISSUE THREAD

**Issue by tinohager** [minio/minio-dotnet#299]
Currently there are two packages on nuget but one i think is outdated.
https://www.nuget.org/profiles/minio

Add an info in the description or disable the package in the nuget management. For me it seems at first sight that the old package should be the new one because it is the core version.

**Comment by nitisht** [comment]
Thanks for reporting @tinohager

**Comment by harshavardhana** [comment]
Its unfortunately not possible to fully delete, but we have unlisted all the releases under Minio.NetCore

Minio.NetCore has been long integrated into Minio
