### ISSUE TITLE
ListObjectsAsync Alternative

### ISSUE THREAD

**Issue by tinohager** [minio/minio-dotnet#300]
Hi,

Is an alternative Method available to get some Files of a bucket? The method `ListObjectsAsync` is very complex to implement. I also think that the implementation is wrong I don't see a `Task<>` as returning here anywhere. I search a method simular to this [ListingObjectKeysUsingNetSDK](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingNetSDK.html)

**Comment by poornas** [comment]
@tinohager, did you check out the ListObjectsAsync example [here](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/ListObjects.cs) ? Both IObservable and Task are comparable implementations - you can convert the IObservable to a Task if you want all the objects returned at once - refer BufferAllAsync function in  [this blog](https://blogs.msdn.microsoft.com/flaviencharlon/2012/08/06/taskt-vs-iobservablet-when-to-use-what/)

**Comment by tinohager** [comment]
@poornas I just don't have a simple method to return the content as an array without any additional code.

**Comment by sebastianbk** [comment]
@tinohager If you use `System.Linq`, you can the following:

```csharp
await minioClient.ListObjectsAsync(bucketName, prefix, false).ToAsyncEnumerable().ForEachAsync(item =>
{
    // Work with the item here
});
```

Doing so, you can treat the results as an array.

**Comment by kannappanr** [comment]
@tinohager Closing this issue based on the workaround provided above.

**Comment by tinohager** [comment]
@sebastianbk It not work in my test case. with .net 4.7.2
