### ISSUE TITLE
ListenBucketNotification is not supported?

### ISSUE THREAD

**Issue by RonSijm** [minio/minio-dotnet#304]
min.io has client libraries:
https://docs.min.io/docs/dotnet-client-api-reference.html
https://docs.min.io/docs/golang-client-api-reference.html
https://docs.min.io/docs/python-client-api-reference.html
https://docs.min.io/docs/java-client-api-reference.html
https://docs.min.io/docs/javascript-client-api-reference.html 

For some reason ListenBucketNotification is only missing from the .net package.

It seems like at some point someone did make an attempt, but never finished:

https://github.com/minio/minio-dotnet/blob/master/Minio/ApiEndpoints/IBucketOperations.cs#L111

**Comment by kannappanr** [comment]
@RonSijm We do not have it yet in `dotnet`. Please feel free to send a PR, if you can. We would love to have constributions from the community.

**Comment by kannappanr** [comment]
@RonSijm Closing this issue now as we do not have enough cycles to get to it right away. Please feel free to send a PR. We will get to this issue once we are done with our higher priority tasks.

**Comment by harshavardhana** [comment]
Re-opening since we have a new PR #370
