### ISSUE TITLE
The authorization header is malformed; the region is wrong; expecting 'us-east-1'

### ISSUE THREAD

**Issue by yuribsl** [minio/minio-dotnet#306]
I'm using the below code and getting the region error, i was getting this error when trying to upload a base64 image using C# MemoryStream.
Funny thing, 5 days ago i successfullly uploaded a image ( without using any streams, just setting a filepath in PutObjectAsync overload ) to the bucket, but i can't do it again, i don't remember if the code was different ( i don't think so ).

My code:

            try
            {
                MinioClient minio = new MinioClient("myurl", "accesskey", "secretkey","us-east-1").WithSSL();
                
                var buckets = await minio.ListBucketsAsync();
            
                await minio.PutObjectAsync("bucketname", "arquivo2", "C:\\Users\\yuri_\\Pictures\\apple_web.png", "image/png");
            catch (Exception ex)
            {

                throw;
            }

**Comment by kannappanr** [comment]
@yuribsl Thanks for reporting this issue. Can you also please add more information to the issue like, which S3 server you are connecting? If `MinIO`, version of `MinIO` in use here etc.

Version of `minio-dotnet` SDK that you are using? What has changed between when it worked and now?

**Comment by yuribsl** [comment]
Well i fixed it yesterday, i reinstalled SDK and removed a previous version of MiniO that was installed toghether with MiniO .net Core, i had reinstalled it before but for some reason it was back there.
I can upload now normal files and base64 files.
The error was only misleading.
Thanks for the attention anyway.

**Comment by kannappanr** [comment]
@yuribsl Thanks for getting back to us. Closing this issue now.
