### ISSUE TITLE
GetObjectAsync how to

### ISSUE THREAD

**Issue by yuribsl** [minio/minio-dotnet#307]
Hi, i don't know if this is the right place to ask this. But i have succesfully uploaded a file to a bucket and now i want to download it.
By using GetObjectAsync and setting filepath like this 

`await minio.GetObjectAsync(_configuration["S3Bucket:bucketName"], "C:\\Users\\ybligorio\\Downloads", "myfile");
`
I get a corrupted pdf ( yes i downloaded directly from bucket and it's ok )

and using FileStream like this:

```
 using (FileStream source = new FileStream("C:\\Users\\ybligorio\\Downloads\\abc.pdf", 
   FileMode.Create))
            {
                await minio.GetObjectAsync(_configuration["S3Bucket:bucketName"], downloadNf, 
                (stream) =>
                { 
                    source.CopyTo(source);
                });
            }
```
I get an empty pdf.
Any ideas?

**Comment by yuribsl** [comment]
Ok delete my post lol i was just passing the filename without pdf extension

**Comment by kannappanr** [comment]
@yuribsl Can this issue be closed?

**Comment by kannappanr** [comment]
@yuribsl Closing this issue. Please feel free to reach out to us on slack if you have further questions.
