### ISSUE TITLE
can not set download json policy for local host in minio using .net core sdk

### ISSUE THREAD

**Issue by dsonjohn** [minio/minio-dotnet#314]
i dont know how set policy json for set download policy to bucket. how i set "resource" and "action" parameters?

**Comment by kannappanr** [comment]
@dsonjohn You can do something like

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket"
      ]
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket/*"
      ]
    }
  ]
}

```
where `mybucket` in the bucket name

**Comment by dsonjohn** [comment]
i need to set this fields for localhost like this : localhost:9000/mybucket. how can i do it?
how i set fields?
for example i tried "Resource": [
        "localhost:9000/mybucket/*"
      ]
but it dont work!

**Comment by kannappanr** [comment]
You can use https://awspolicygen.s3.amazonaws.com/policygen.html to generate the policy.

`Resource` here should be something like `"arn:aws:s3:::mybucket/*"` It is called `Amazon Resource Name` . Here is the description about it in the link that I have posted above 
```
ARN should follow the following format: arn:aws:s3:::<bucket_name>/<key_name>.
Use a comma to separate multiple values.
```

**Comment by kannappanr** [comment]
@dsonjohn Closing this issue as answered. Please feel free to re-open the issue if you feel otherwise
