### ISSUE TITLE
minio restfull api

### ISSUE THREAD

**Issue by codema2015** [minio/minio-dotnet#316]
with asp.net , how to use restfull api?

**Comment by kannappanr** [comment]
we have examples at https://github.com/minio/minio-dotnet/tree/master/Minio.Examples . They are not specific to ASP.NET. I found this example that talks about using AWS .Net SDK with asp.net
https://www.codeproject.com/Articles/874149/Store-Files-in-Amazon-S-using-AWS-SDK-in-ASP-NET-M

replacing AWS SDK with Minio SDK should be staright forward. Please let us know if you have further questions.

**Comment by codema2015** [comment]
thanks

**Comment by kannappanr** [comment]
@codema2015 Closing this issue as answered. Please feel free to reach out to us if you have further questions.
