### ISSUE TITLE
how to config server？

### ISSUE THREAD

**Issue by codema2015** [minio/minio-dotnet#317]
when install in windows, how to config server？
1：how to set server ports？
2：how to set server ip?
3：how to start  especial ip? Prohibit other IP。

**Comment by kannappanr** [comment]
PTAL https://www.youtube.com/watch?v=dIQsPCHvHoM

The video here is for Linux, but it is pretty similar in windows also. Please reach out to us on slack at https://slack.min.io for questions like these.

**Comment by kannappanr** [comment]
@codema2015 Closing this as answered. Please feel free to reach out to us on slack.
