### ISSUE TITLE
SignatureDoesNotMatch when port is 80

### ISSUE THREAD

**Issue by DouglasMarsh** [minio/minio-dotnet#321]
I've discovered an issue with using the minio dotnet client when connected to a minio server over port 80.
The signature generated by the client sets host header using the following code: 
`SetHostHeader(request, client.BaseUrl.Host + ":" + client.BaseUrl.Port);`
This is V4Authenicator.cs: line 114
The issue is, the server doesn't seem to include the port number with host resulting in a signature mismatch.

I've verify buy running the dot-net samples code and removing port number from SetHostHeader. The signature mismatch issue goes away.

**Comment by kannappanr** [comment]
@DouglasMarsh Thanks for reporting the issue. We will take a look and get back to you.

**Comment by poornas** [comment]
@DouglasMarsh, are you running minio behind a proxy? If so - please check if  the proxy is overwriting host header. 

With minio server running on port 80, not able to repro the bug that you see.

**Comment by DouglasMarsh** [comment]
yes minio is behind a nginx ingress running  kubernetes. 
I will check if the ingress is overwritting the host header

**Comment by poornas** [comment]
ping @DouglasMarsh

**Comment by SpeedPing** [comment]
This also happens when using a different RestSharp version. Using RestSharp v106.5.0 or higher, the same signature mismatch error is returned for multipart uploads. Tested on dotnet core 2.2.

**Comment by poornas** [comment]
> This also happens when using a different RestSharp version. Using RestSharp v106.5.0 or higher, the same signature mismatch error is returned for multipart uploads. Tested on dotnet core 2.2.

@SpeedPing, can you turn on http tracing for minio server by running `mc admin trace -v -a myminio-alias`  and run minio-dotnet sdk with client.SetTraceOn() and share the output? We are not able to repro this on linux running .netcore examples from [here](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Program.cs) with endpoint at port 80. Are you using nginx as well? If so, make sure that host headers are not being overwritten by your proxy.

**Comment by SpeedPing** [comment]
Tested on 2 completely different networks&machines with local and remote setup, same outcome.

Steps to reproduce on windows:
1) Create dot netcore 2.2 console project
2) Reference latest minio-dotnet
3) Reference latest RestSharp
4) Invoke PutObjectAsync with a stream and size above 5 Mb
5) Wait for results

mc admin results:
[fail.txt](https://github.com/minio/minio-dotnet/files/3586997/fail.txt)
[success.txt](https://github.com/minio/minio-dotnet/files/3586998/success.txt)

**Comment by SpeedPing** [comment]
@poornas Can you validate this issue?

**Comment by poornas** [comment]
> @poornas Can you validate this issue?

@SpeedPing , was not able to repro this issue with the latest 3.1.4 version. Are you able to run the sample [project](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Minio.Examples.csproj) successfully?  Just change the endpoint and credentials to your local minio server and test your upload against that.

**Comment by Maximkaaa** [comment]
@poornas I've faced the same issue, but connecting to a different s3 server. For my work I need to use Yandex S3, which works great with official Java tools and python boto. But MinIO client failes to authenticated with it for this reason. It seems that the server implementation does not expect default :80 port to be present in the host header.

In my case it seems to be a bug in the server implementation. Still other tools work fine with it since they do not include the :80 port in the host header. Do you think it can be beneficial to also not include default port, as more popular tools do, to provide better support for different S3 server implementations? If so, I can make a PR.

**Comment by sergei66666** [comment]
@Maximkaaa Just to note: yandex team fixed it, now it works fine.
