### ISSUE TITLE
Deadlocks due to ConfigureAwait(false) not used in ExecuteTaskAsync method

### ISSUE THREAD

**Issue by ChipRadon** [minio/minio-dotnet#325]
We are experiencing deadlocks because there is no .ConfigureAwait(false) used in method call:
IRestResponse response = await this.restClient.ExecuteTaskAsync(request, cancellationToken);
https://github.com/minio/minio-dotnet/blob/master/Minio/MinioClient.cs#L367

Relates to #219

**Comment by nitisht** [comment]
Thanks for reporting @ChipRadon we'll take a look

**Comment by antonchaika** [comment]
Is there any update on this?
