### ISSUE TITLE
"CopyObjectAsync" gives an error with Server Side Encryption

### ISSUE THREAD

**Issue by GambitKZ** [minio/minio-dotnet#331]
The version of the package which I use is 3.1.1.

I'm using Server Side Encryption when I'm saving the object.
The Server Side Encryption object is generated by following command:
```
Aes aesEncryption = Aes.Create();
aesEncryption.KeySize = 256;
aesEncryption.GenerateKey();
ssec = new SSEC(aesEncryption.Key);
```
and later used everywhere for this object.

It works perfectly fine with Put/Get/Stat methods, but as soon as I try to use "Copy" command, by putting the object above as a source and destinations as:
`await minio.CopyObjectAsync(srcBucketName, fileName, destBucketName, sseSrc: ssec, sseDest: ssec);`
I got the following error "MinIO API responded with message=Requests specifying Server Side Encryption with Customer provided keys must provide a valid encryption algorithm.".

If I moving the un-encrypted file to another bucket and encrypted it there with code:
`await minio.CopyObjectAsync(srcBucketName, fileName, destBucketName, sseDest: ssec);`
It works perfectly.

All I need to do is to move the encrypted object to a different bucket with the same Server-Side Encryption key.

Can someone help me with this issue?

**Comment by kannappanr** [comment]
You are supposed to use SSECcpy PTAL at https://github.com/minio/minio-dotnet/blob/1c5bf0ed14909b6ca7f6ba4fa4b6d4da929b5802/Minio.Examples/Program.cs to learn how it should be used

**Comment by kannappanr** [comment]
Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions
