### ISSUE TITLE
Minio not working when I have special characters in access key.

### ISSUE THREAD

**Issue by cocapasteque** [minio/minio-dotnet#339]
Hello,

I noticed that minio client would send me an invalid presigned url if I have special characters in my access key. After a little bit of research I found that there was [a PR to fix this](https://github.com/minio/minio-dotnet/pull/221). But the changes from this PR got removed with the very next commit.

I can upload files to minio but when trying to access them with a presigned url I get this error : 
**The access key ID you provided does not exist in our records.**

**Comment by kannappanr** [comment]
@cocapasteque Thanks for filing this issue. We will take a look and get back to you.

**Comment by cocapasteque** [comment]
Downloaded the repo on my local machine and replacing this line in V4Authenticator.cs (line 298)):

    requestQuery += "X-Amz-Credential="
                + this.accessKey
                + Uri.EscapeDataString("/" + this.GetScope(region, signingDate))
                + "&";

With this : 

    requestQuery += "X-Amz-Credential="              
                + Uri.EscapeDataString(this.accessKey + "/" + this.GetScope(region, signingDate))
                + "&";

Fixed it for me, I can get correct presigned url again. But have to build a custom binary for my app then.
Any reason why this bit of code got removed ?
