### ISSUE TITLE
HTTP Head extremely slow 

### ISSUE THREAD

**Issue by StephanyBatista** [minio/minio-dotnet#340]
c# client, version 3.1.4.0
latest docker server
ASP.NET Full Framework, version 4.6.1

We are experiencing a slowdown with min.io and we find out throut Application Insights that this slowdown is always related to HTTP Head as shown below, but de HTTP Get is fast

![image](https://user-images.githubusercontent.com/6475229/66229810-a9dd5c80-e6b0-11e9-88d3-ddc7355e1aca.png)

Analyzing the min.io code, I realized that in the GetObjectAsync method calls the StatObjectAsync method, but without assigning to any variable the return of the asynchronous method. I saw that the StatObjectAsync method does an HTTP Head to test the existence of the object.

```csharp
public async Task GetObjectAsync(string bucketName, string objectName, Action<Stream> cb, ServerSideEncryption sse = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            await StatObjectAsync(bucketName, objectName, sse: sse, cancellationToken: cancellationToken).ConfigureAwait(false);

            var headers = new Dictionary<string, string>();
            if (sse != null && sse.GetType().Equals(EncryptionType.SSE_C))
            {
                sse.Marshal(headers);
            }
            var request = await this.CreateRequest(Method.GET,
                                                bucketName,
                                                objectName: objectName,
                                                headerMap: headers)
                                    .ConfigureAwait(false);
            request.ResponseWriter = cb;

            var response = await this.ExecuteTaskAsync(this.NoErrorHandlers, request, cancellationToken).ConfigureAwait(false);
        }
```

1 - Has anyone had this kind of problem?
2 - Is there any reason why in the GetObjectAsync method is it necessary to call StatObjectAsync?

**Comment by poornas** [comment]
The StatObjectAsync is required to check if object exists - this should be quick. Can you turn on tracing on server side with mc client - `mc admin trace myminio-alias --verbose --all' and paste the http trace?

**Comment by StephanyBatista** [comment]
Thanks for the help, I will ask staff who maintain the server.

But for me to understand, what is the purpose of checking the file if I will get after it?

**Comment by poornas** [comment]
The GetObjectAsync variant with filename in arguments requires it @StephanyBatista , to determine the object size. Is your application using the stream callback variant of this function?

**Comment by StephanyBatista** [comment]
Yes, 

```csharp
        public byte[] Consultar(string nomeDoArquivo)
        {
            _clienteMinIo = MinIOConfiguracao.conectar();
            _clienteMinIo.GetObjectAsync(
                _nomeDoBucketNoMinIo,
                $"{_nomeDaPastaNoMinIo}/{nomeDoArquivo}",
                (arquivoRetornado) => { ObterDadosDo(arquivoRetornado); })
                .Wait();
            return _arquivo;
        }

        private void ObterDadosDo(Stream arquivoRetornado)
        {
            var memoryStream = new MemoryStream();
            arquivoRetornado.CopyTo(memoryStream);
            _arquivo = memoryStream.ToArray();
        }
```

**Comment by poornas** [comment]
@StephanyBatista, are you able to download the object using this [example](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/GetObject.cs) after changing endpoint and creds in Minio.Examples project?

**Comment by StephanyBatista** [comment]
Your code for me the only difference is the "await". 

This will improve?

Sorry if I did not understand

**Comment by poornas** [comment]
> This will improve?
Can you post a simple reproducer project - you may be blocking on the main thread. Also, please post the server side trace. Were you able to encounter the same issue on the example project?

**Comment by StephanyBatista** [comment]
Hi

We discovered the problem. I was saving many files in the same folder. More than 750k files.
After I spread that files to others folders (Year/Month/Day/Hour the problem ended.

**Comment by StephanyBatista** [comment]
Hi

We discovered the problem. I was saving many files in the same folder. More than 750k files.
After I spread that files to others folders (Year/Month/Day/Hour the problem ended.
