### ISSUE TITLE
MC Share for dotnet client

### ISSUE THREAD

**Issue by StephanyBatista** [minio/minio-dotnet#348]
Hi,
I saw the command mc share that share files by a time through a link. I did not find this for dotnet client.
Sorry if exists and I did not find

**Comment by poornas** [comment]
https://docs.min.io/docs/dotnet-client-api-reference.html#presignedGetObject is what you are looking for

**Comment by StephanyBatista** [comment]
Ok, thanks!

**Comment by benyaminl** [comment]
@poornas is there anyway to update the preSigned object on docs https://docs.min.io/docs/dotnet-client-api-reference.html#presignedGetObject so we can make it well, searchable with Share keyword? Is that okay to edit the docs?
