### ISSUE TITLE
Some files dit not understand by min.io

### ISSUE THREAD

**Issue by thiagodsign** [minio/minio-dotnet#349]
Hi,

![image](https://user-images.githubusercontent.com/31048708/67805312-24f32200-fa67-11e9-8000-4157c6c5f238.png)

In the image above, only exists pdf files, but when I upload the file by a app that uses client dotnet, the min.io does not understand that the file is a pdf. But when I upload the file by the min.io, it understand the file as pdf. 

What do I need to do so that the min.io can understand the file as pdf?

What problem do I have? I want pre signed file URL to append in the HTML as viewer, but when I try the file is downloaded. But to the other files, the browser opens correctly

**Comment by poornas** [comment]
@thiagodsign, you could try the PresignedPostPolicyAsync API call where you can set the content type - https://docs.min.io/docs/dotnet-client-api-reference.html#presignedPostPolicy instead of the PresignedPutObjectAsync call

**Comment by kannappanr** [comment]
@thiagodsign Closing this as answered. Please feel free to reach out to us if you have further questions
