### ISSUE TITLE
InvalideEndpointException .net core 3

### ISSUE THREAD

**Issue by otmanel31** [minio/minio-dotnet#350]
Hi,

I'm trying to connect to remote minio using .net core sdk and got "http://my-ip-address:9000/: No path allowed in endpoint.: Minio.Exceptions.InvalidEndpointException: Minio API responded with message=No path allowed in endpoint."

It works well using Java SDK but not with .NET CORE sdk 3. Any hints ?

**Comment by otmanel31** [comment]
I had a piece of code as example below .... when i try to connect to my remote minio that didn't work ... but for play.min.io .... ([as describe in this tutorial)](https://docs.min.io/docs/dotnet-client-quickstart-guide.html) that works .... 

```
private static MinioClient m = new MinioClient("http://my_ip_address:9000/", "something", "secret");
/*private static MinioClient m = new MinioClient("play.min.io",
                "Q3AM3UQ867SPQQA43P2F",
                "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
                ).WithSSL();*/
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var getListBucketsTask = m.ListBucketsAsync();
            // Iterate over the list of buckets.
            foreach (Bucket bucket in getListBucketsTask.Result.Buckets)
            {
                Console.WriteLine(bucket.Name + " " + bucket.CreationDateDateTime);
            }

        }
```

**Comment by otmanel31** [comment]
That works by removing "http:// " prefix

**Comment by dominicjordan** [comment]
Indeed removing http:// or https:// works for me as well. Thanks!!
