### ISSUE TITLE
Add/Remove/List User and Change password

### ISSUE THREAD

**Issue by nerkapawel** [minio/minio-dotnet#352]
Hi,

I have problem, because i dont see any method in code which allow me to execute add/remove list user. I need to do this via .net app and i dont have access to machine with minio by ssh (so i can't execute commands e.g. by mc.exe)

Is there any way to do this by simple http requests??

**Comment by harshavardhana** [comment]
No, you need to use `mc` for administrative tasks such as add, remove, list user.

**Comment by renemadsen** [comment]
Revisiting this issue.

Is there any plans of supporting this in the future?

In order for me to migrate from AWS to minio this is a requirement, otherwise it would require to create C# code that would call the mc, which is not optimal for the above tasks.

**Comment by harshavardhana** [comment]
No @renemadsen please use our Go SDK for admin operations

**Comment by renemadsen** [comment]
> No @renemadsen please use our Go SDK for admin operations

Okay, but where do I find the documentation for admin oprations done with the go SDK, i cannot find it at https://github.com/minio/minio-go or at https://docs.min.io/docs/golang-client-api-reference.html

**Comment by harshavardhana** [comment]
> Belive I found it at https://github.com/minio/madmin-go I guess?

https://pkg.go.dev/github.com/minio/madmin-go?utm_source=godoc
