### ISSUE TITLE
Instrument with DiagnosticSource

### ISSUE THREAD

**Issue by ElderJames** [minio/minio-dotnet#363]
Using diagnostics allows users to get more runtime event data, which is helpful for distributed tracking systems.

HttpClient has provided support for diagnostics.I find the `LogRequest` method in MinioClient is used to output some logs about minio, we can also send them to DiagnosticSource.

Diagnositics doc :
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md

**Comment by kannappanr** [comment]
@ElderJames Please feel free to send a PR

**Comment by harshavardhana** [comment]
**Please upgrade to the latest release** and re-open if seen again.
