### ISSUE TITLE
CopyObjectAsync is much slower than mc tool

### ISSUE THREAD

**Issue by ngbrown** [minio/minio-dotnet#372]
In `CalculateMultiPartSize`, which is triggered if the source is over 5 GiB, it appears the copy is made to maximize the number of parts (which is 10,000), bounded by the minimum part size (5 MiB).

https://github.com/minio/minio-dotnet/blob/b7e7adff75bfe63842063baa6b0f46b1054d0957/Minio/Helper/utils.cs#L235

On the other hand, the `mc` command line copies with much fewer parts.  It seems to optimize for a higher part size (500 MiB), or 100 times larger than the minimum part size.

The speed difference is significant.  A 7 GiB file copies between buckets on the commandline in 1 minute.  With the .net client, I canceled after 25 minutes, and it was only 56% done.

Is there any way to tune this?

**Comment by kannappanr** [comment]
@ngbrown Thanks for filing this issue. As far as `copyobjectpart` is concerned, I agree with you since the data is already in the backend. We can use 5GB part size.

**Comment by ngbrown** [comment]
The go client seems to do it quite a bit differently by getting the number of parts first:

https://github.com/minio/minio-go/blob/8e3928466d18a04caf35a76a0f4a41d65ab1c9fc/api-compose-object.go#L525

I did start a branch to use be able to use different minimum part sizes.  It's not tune-able like I suggested, but it is a lot faster.

https://github.com/ngbrown/minio-dotnet/commit/7f2acd121d22dd59e01b2295d4bde71c03ec5175

If you have a suggestion on which way to go, I can update my branch and start a pull request.

**Comment by poornas** [comment]
@ngbrown, the reason mc is much faster than dotnet SDK here is because minimum part size used by mc is 128MiB vs the much lower 5MiB on dotnet SDK. We can make the part size configurable so that you can optionally bump it up if your network can handle it.

**Comment by kannappanr** [comment]
@ngbrown, we can set the part size in the case of `CopyObjectPart` to `5GiB` and the `PutObjectPart` can still be `5MiB`. In another PR we can set the default to be `64MiB`, but also allow clients to override that value. Also, please use already defined constants for the numbers, `MaximumPartSize` and `MinimumPartSize`

**Comment by ngbrown** [comment]
Regarding setting the part size to `5GiB`, I used `512 MiB` because parts completing appears to be the only way that there can be any progress reported on server copies.

I realize there's no progress reported in the .NET client right now, but [`IProgress<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.iprogress-1?view=netframework-4.8) is a globally available interface for exactly that sort of thing.

@kannappanr, You mentioned using the existing constants, `MaximumPartSize` and `MinimumPartSize`.  These values are defined by the S3 API, so I'm not sure where I would have used them in my code changes.  Is the idea that those would be directly set as the means of configuring?  Currently the constants class is `internal`.

I would suggest adding two new constants, `DefaultUploadPartSize` and `DefaultServerTransferPartSize`, then use those as the defaults for configuration.  Doing the configuring in a constructor configuration object seems to be the standard way in .NET libraries.  I would add a `MinioClient` constructor overload using a new configuration object and obsolete the current one.

**Comment by BigUstad** [comment]
PR #530 has the fix to speed up PUT & COPY operations.
