### ISSUE TITLE
Split MinioClient implementation to allow access to advanced functions

### ISSUE THREAD

**Issue by ngbrown** [minio/minio-dotnet#376]
I have a need to directly access the multi-part functions, `NewMultipartUploadAsync`, `GetListPartsAsync`, and `CompleteMultipartUploadAsync`.

I can switch to doing these in the AWS .NET SDK, but I would like to improve this client instead.  I would move these private functions into a separate `MinioClientAdvanced` class and make them available on a `client.Advanced` property.

Any thoughts?

**Comment by harshavardhana** [comment]
This SDK is meant for higher level APIs, for low level APIs fork the project and use it yourself.

It is not part of the design to expose those details.

**Comment by ngbrown** [comment]
For reference, it wasn't nearly as invasive as I originally described.

I added an `MinioClientAdvanced` class and have the following functions that pass through to `internal` functions on `MinioClient`.

- `NewMultipartUploadAsync()`
- `PresignedUploadPartAsync()`
- `ListParts()`
- `RemoveUploadAsync()`
- `CompleteMultipartUploadAsync()`

I can now use `MinioClient` on the server-side for web clients that support multipart s3 uploads with signed URLs like Uppy.

See the following comparison: https://github.com/minio/minio-dotnet/compare/master...ngbrown:add-advanced

**Comment by harshavardhana** [comment]
@ngbrown I understand what you are thinking but that is not the intention of this SDK exposing these functionalities requires us to abide by semver API restrictions and we need to make sure we don't break them in future as applications might depend on them. 

This is an unnecessary burden for us - if you want to simply have REST calls with signature v4 you don't need this library you can write this entirely in your project.
