### ISSUE TITLE
Method not found: 'Void RestSharp.RestRequest.set_XmlSerializer(RestSharp.Serializers.ISerializer)'

### ISSUE THREAD

**Issue by nudzo** [minio/minio-dotnet#384]
Possible the same issue as #296 
Running on the 3.1.3 dotnet core.
```
System.MissingMethodException: Method not found: 'Void RestSharp.RestRequest.set_XmlSerializer(RestSharp.Serializers.ISerializer)'.
   at Minio.MinioClient.SetBucketNotificationsAsync(String bucketName, BucketNotification notification, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Minio.MinioClient.SetBucketNotificationsAsync(String bucketName, BucketNotification notification, CancellationToken cancellationToken)
   at Minio.MinioClient.RemoveAllBucketNotificationsAsync(String bucketName, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 373
```

**Comment by poornas** [comment]
Which version of Restsharp are you using in your dependencies?

**Comment by nudzo** [comment]
I have no direct RestSharp dependency, just prototyping in F# scripts.
It loads following:
```
>>>> /Users/nudzo/.nuget/packages/fsharp.data/3.3.3/typeproviders/fsharp41/netstandard2.0/FSharp.Data.DesignTime.dll
>>>> /Users/nudzo/.nuget/packages/fsharp.data/3.3.3/lib/netstandard2.0/FSharp.Data.DesignTime.dll
Using: /Users/nudzo/.nuget/packages/fsharp.data/3.3.3/typeproviders/fsharp41/netstandard2.0/FSharp.Data.DesignTime.dll
Binding session to '/Users/nudzo/.nuget/packages/restsharp/106.10.1/lib/netstandard2.0/RestSharp.dll'...
```
Thus RestSharp@106.10.1. I hit this for `RemoveAllBucketNotificationsAsync`, some other methods works OK.

**Comment by poornas** [comment]
@nudzo, the SDK uses Restsharp@"106.3.1" which used IXmlSerializer - is it possible to downgrade to this Restsharp version as a turnaround? The minio-dotnet pkg needs to be updated to the latest Restsharp@106.10.1 - however this in turn breaks the authorization signature sent by the SDK. Will send a fix after resolving the issue.

**Comment by nudzo** [comment]
@poornas Thanks, `RestSharp@106.3.1` works OK. I don't use RestSharp, it's just 3rd party dependency for me, so I can downgrade. May be think of fixing RestSharp version in minio-dotnet deps, cause it's just like `RestSharp (>= 106.3.1)`, so then latest one was downloaded in my case.

**Comment by SpeedPing** [comment]
@poornas 
If this is still relevant: https://github.com/minio/minio-dotnet/issues/336#issuecomment-602731831
This issue is initially provoked by Restsharp's resource path change, which now seems to not include query parameters anymore.

**Comment by novicov** [comment]
I have the same problem with **StatObjectAsync** method. 
`Void ParseError(RestSharp.IRestResponse)`
