### ISSUE TITLE
NRE for several operations when not specifying region

### ISSUE THREAD

**Issue by IsaackRasmussen** [minio/minio-dotnet#388]
With latest package 3.1.10 and DotNet Core 3.1, I get NRE for several operations when opening a backend without specifying the optional region. This is for example not needed for Backblaze B2.
It seems it will work if I just specify any value for region.

This seems to work without region:
- ListBucketsAsync

These do not work
- BucketExistsAsync
- PutObjectAsync

Also, using .WithSSL doesn't update the endpoint property to "https://"

**Comment by JonOdgaard** [comment]
Also an issue with StatObjectAsync() it seems
If bucket region is not specified, the minio client attempt to fetch the bucket region over http
But since SSL is enabled, server only has https bindings

**Comment by RozDavid** [comment]
Hey guys, any update how can we enable _https_ without specifying the region parameter? 
The `.WithSSL().Build()` functions doesn't seem to be supported by the current version anymore that could force it.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
