### ISSUE TITLE
GetRegionFromEndpoint introduces significant delay in requests

### ISSUE THREAD

**Issue by geluk** [minio/minio-dotnet#393]
When a request is made to an endpoint with a long enough non-AWS hostname without specifying the region, the regex inside `GetRegionFromEndpoint` can take several seconds to complete. This slows down requests by quite a lot.

This happens because the regex contains two nested quantifiers (`{1,61}` and `*?`), which causes an exponential amount of backtracking on all endpoints that do not match the regex.

As an example, the regex will take about 25 seconds to run on my machine when given this endpoint: `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.local`

I added the endpoints from the unit tests and an example endpoint to regex101 [here](https://regex101.com/r/8FGJD2/2/), which also warns about this:

>Catastrophic backtracking has been detected and the execution of your expression has been halted.

It would be nice if this regex could be simplified so it does not contain any nested quantifiers anymore. I would like to submit a PR for this, but I'm not sure if there are any other types of endpoints that need to be accounted for (besides the ones specified in the unit tests).

**Comment by kannappanr** [comment]
cc @poornas

**Comment by poornas** [comment]
@geluk, please feel free to send a PR - region applies only to aws endpoints, so if endpoint contains `amazonaws.com` this method can just return empty string. Other types of s3 endpoints are like [here](https://github.com/minio/minio-go/blob/73284c9cbf05caee67b725c8d0bcb308dec107fc/pkg/s3utils/utils.go#L105)

**Comment by geluk** [comment]
@poornas thanks! I have created a PR.
