### ISSUE TITLE
[Suggestion] Fixes for MinioException.

### ISSUE THREAD

**Issue by ig-sinicyn** [minio/minio-dotnet#396]
The MinioException has two public properties, `message` and `response`.

I'd suggest to use standard `Exception.Message` property. Client code may log only ex.Message. Having an empty message mages troubleshooting much harder. As it is for now, the `MinioException.Message` is null for some exceptions, BucketNotFoundException as example.

The `response` property should be named in PascalCase co conform c# naming guidelines. In addition, I believe it should be set for all exceptions where possible. Especially for the InternalClientException.
Currently there is no way to distinguish "server unavailable" error from "invalid object name" error. Both of them throw same InternalClientException with same properties.

**Comment by kannappanr** [comment]
@ig-sinicyn Please feel free to send a PR.

**Comment by ig-sinicyn** [comment]
Done, #398
