### ISSUE TITLE
[Regression] ListObjects does not respect recursive=false 

### ISSUE THREAD

**Issue by Maximkaaa** [minio/minio-dotnet#399]
I've faced an issue while updating from Nuget package version 3.1.10 to 3.1.11.

The newer version's method ListObjects always returns results as if recursive flag is set to true. The same code returns different result whenever I change the version of the Nuget package.

I've also checked the current (not published) build, the issue is also there.

**Comment by kannappanr** [comment]
@Maximkaaa Thanks for filing this issue. We will take a look.

**Comment by poornas** [comment]
@Maximkaaa , this is fixed in master branch. It will be fixed in the next release.

**Comment by Maximkaaa** [comment]
Great! Thank you.

**Comment by poornas** [comment]
version 3.1.12 is released - closing this as fixed.
