### ISSUE TITLE
The SetPolicyAsync api is change?

### ISSUE THREAD

**Issue by yilezhu** [minio/minio-dotnet#402]
The api document like
`SetPolicyAsync(string bucketName, string objectPrefix, PolicyType policyType)`
but the latest source code is like this
` public async Task SetPolicyAsync(string bucketName, string policyJson, CancellationToken cancellationToken = default(CancellationToken))`

If I want to set up a permanent access url .How should I set it up？
There are no settings here for `PolicyType.READ_ONLY`

**Comment by poornas** [comment]
See [this](https://github.com/minio/minio-dotnet/blob/87aab4a0796e00a1cc77f8c35b1133999fd020a1/Minio.Examples/Cases/SetBucketPolicy.cs) example - the API changed to require the full policy json, The CN version of the API.md is outdated, we will need to fix that.
