### ISSUE TITLE
Metadata values in StatObjectAsync are converted to lowercase.

### ISSUE THREAD

**Issue by ngbrown** [minio/minio-dotnet#408]
This line was introduced in #356:
https://github.com/minio/minio-dotnet/blob/148406fd0a3918c9ed12c89a8c8f240650801ec7/Minio/ApiEndpoints/ObjectOperations.cs#L843

The metadata values are stored with correct casing in Minio, but the `StatObjectAsync` is converting them to lowercase on retrieval.

Are there real cases where the values would be prefixed with `x-amz-meta-`? I thought this was only for the header names (key).

I don't expect my metadata values to be converted to lowercase.  An example is a `Content-Disposition` header where filenames are case sensitive.

**Comment by kannappanr** [comment]
@ngbrown Are you saying that the values are also being lower-cased and not just the headers themselves?

**Comment by ngbrown** [comment]
@kannappanr Yes, the values are being lowercased, replaced, then assigned to the outgaing `metaData` dictionary.

I have a branch that fixes this, but before submitting a pull request, I wanted to know why `x-amz-meta-` would ever be in the value of a header?

Branch using a Regex expression:
https://github.com/minio/minio-dotnet/compare/master...ngbrown:patch-stat-metadata-value

**Comment by kannappanr** [comment]
@ngbrown I think the `Header` will have prefix like `X-Amz-Meta..` and that should be the one to be stripped and not the value itself.

**Comment by ngbrown** [comment]
I understand, but it could also be a breaking change without some care.  To prevent breaking library user expectations, the return `metaData` should have both the original header name and the trimmed header name.  I'll update my branch and make a pull request.

**Comment by ngbrown** [comment]
I've opened #409 for this.
