### ISSUE TITLE
How to consume minio cluster.

### ISSUE THREAD

**Issue by AlexanderButs** [minio/minio-dotnet#410]
Hey, guys.

Spent hours to find info about how to consume minio cluster (distributed deployment).
If I have 3 minio nodes which make single cluster, each node has its own endpoint, then how can I consume all three nodes by client library to have loadbalance and fault tolerance architecture? Everything I can feed to client library is one endpoint unfortunately. Did I miss how minio cluster works? Usually client libraries get a list of endpoints to use for requests, but not in minio case, I guess.

Could you clarify, please?

Thanks.
Alex.

**Comment by kannappanr** [comment]
Please feel free to send a PR to handle this scenario.

**Comment by sergei66666** [comment]
I'am not good in it. but you can create load balancer. You will have one url of load balancer which you feed to minio-dotnet

**Comment by kannappanr** [comment]
PTAL https://github.com/minio/sidekick This can be used on the client side
