### ISSUE TITLE
ObjectNotFoundException Not Thrown

### ISSUE THREAD

**Issue by josetuna** [minio/minio-dotnet#413]
Hil All,

I am running a code like this:
```
try
{
   Action<Stream> callback = some_action;
   await client.GetObjectAsync("bucket", "path/to/file", callback);
}
catch (Minio.Exceptions.ObjectNotFoundException)
{
    // do something...
}
```

This used to work properly some time ago, nut now with the newer version I'm not getting ObjectNotFoundException on the new version (3.1.12).

Instead I'm getting some XML content on the Stream, such as this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message>
<Resource>/bucket/path/to/file</Resource>
<RequestId>160F2FEEB3284B41</RequestId>
<HostId>3L137</HostId></Error>
```

¿Is there any workaround for this? Thanks in advance!

EDIT: I have already verified this works properly in version 3.1.11; so this must be a bug introduced in version 3.1.12

**Comment by kannappanr** [comment]
@josetuna Thanks for reporting this issue. Looks like there has been a regression in the latest version. We will take a look and fix it soon.

**Comment by Praveenrajmani** [comment]
> ObjectNotFoundException

Can you try this `minio.GetObjectAsync(bucketName, objectName, fileName);` instead of accepting a call back? 

And let me know if you see the problem here as well @josetuna

**Comment by Praveenrajmani** [comment]
I just tested with the master. It worked fine for me.

```
using System;
using System.Threading.Tasks;

namespace Minio.Examples.Cases
{
    class GetObject
    {
        // Get object in a bucket
        public async static Task Run(MinioClient minio,
                                     string bucketName = "testb",
                                     string objectName = "issue",
                                     string fileName = "/tmp/my-file-name")
        {
            try
            {
                Console.WriteLine("Running example for API: GetObjectAsync");
                await minio.GetObjectAsync("testb", "issue1", 
                (stream) =>
                {
                     // Uncomment to print the file on output console
                    stream.CopyTo(Console.OpenStandardOutput());
                });
                Console.WriteLine($"Downloaded the file {fileName} in bucket {bucketName}");
                Console.WriteLine();
            }
            catch (Minio.Exceptions.ObjectNotFoundException)
            {
                Console.WriteLine("Bucket  Exception");
            }
            catch (Exception e)
            {
                Console.WriteLine("Any other Exception");
            }
        }
    }
}
```

And i got

```
Running example for API: GetObjectAsync
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>issue1</Key><BucketName>testb</BucketName><Resource>/testb/issue1</Resource><RequestId>160F96B2EFEBADD9</RequestId><HostId>fe574edd-9068-4c29-9be8-791ae00df864</HostId></Error>Bucket  Exception
```

And the error in the response stream is expected. The server writes the XML error in the response which is been printed here.

**Comment by josetuna** [comment]
Hi Praveenrajmani,
Your sample is not working fine... You see the XML error message, but you are not getting an exception properly.
If so, you would see the string "Object  Exception" in the console.
Basically your code is not getting here:

```
            catch (Minio.Exceptions.ObjectNotFoundException)
            {
                Console.WriteLine("Object  Exception");
            }
```

My payload is not an XML, but an AVRO file instead. So it is awkward to try to parse as XML to catch errors.

**Comment by Praveenrajmani** [comment]
> Hi Praveenrajmani,
> Your sample is not working fine... You see the XML error message, but you are not getting an exception properly.
> If so, you would see the string "Object Exception" in the console BEFORE the XML is displayed.
> EDIT: The XML should not get to be displayed at all...
> My payload is not an XML, but an AVRO file instead. So it is awkward to try to parse as XML to catch errors.

@josetuna The exception `Minio.Exceptions.ObjectNotFoundException` is actually being caught. You can see the print message in the output that i have pasted.

The XML is perhaps because of the stream callback that you are passing. `stream` is actually the response stream. The server response will be written to the stream which is correct.

**Comment by josetuna** [comment]
@Praveenrajmani The exception is caught after the stream is processed (in this case, written to console) which is a concurrency issue.
I thought the exception was never thrown because my program crashed while processing the stream.
So the title instead shold be "ObjectNotFoundException concurrency issue".
