### ISSUE TITLE
Does minioclient need to be created every time

### ISSUE THREAD

**Issue by mia01** [minio/minio-dotnet#417]
Hello

I have some questions about using MinioClient.
All the examlle show a new instance being created each time. My question is can I use a MinioClient as a Singleton in my .netcore app?

Secondly, does it need to be disposed after it has been used?

Thirdly,  does MinioClient use a HttpClient internally? If so is it protected from the issue mentioned here: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core

Thanks in advance :)

**Comment by poornas** [comment]
@mia01, you need to instantiate the client only once. All the examples are meant to be run standalone - hence they instantiate a client before invoking a sample call. MinioClient uses RestSharp internally, which in turn uses HttpWebRequest.
