### ISSUE TITLE
Enhancement: pass ObjectStat to callback from GetObjectAsync

### ISSUE THREAD

**Issue by sergei66666** [minio/minio-dotnet#430]
Hello again! :)

Inside `GetObjectAsync` happens two actions:
1) calling `StatObjectAsync`
2) request for content.

So, inside `GetObjectAsync` we already have `ObjectStat`. But in callback only stream (`Action<Stream> cb`).

Now, in case when we need some metadata or other stat info we should call `StatObjectAsync` and `GetObjectAsync` - it is give 3 call to server.

If pass `ObjectStat` in callback - we can save 1 trip to server.

What you think about it?

**Comment by kannappanr** [comment]
@sergei66666 Thanks for the suggestion. We have started adding support for versioning in the sdk. Will take a look at this request.

**Comment by Maximkaaa** [comment]
I was wondering about an opposite thing. The GetObject request together with StatObject works very slowly. In my setting with local MinIO StatObject request takes around 500ms whereas the getting the object itself takes 50ms. (I have a lot of small files) Is there no way to get object without making additional StatObject request?

**Comment by BigUstad** [comment]
Implemented in master branch. Will be available in release soon.
