### ISSUE TITLE
Add support for versioning

### ISSUE THREAD

**Issue by Mattacks** [minio/minio-dotnet#433]
AWS S3 [supports versioning](https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html) 
MinIO [supports versioning](https://github.com/minio/minio/issues/2111) 
The Java client [supports versioning](https://docs.minio.io/docs/java-client-api-reference.html#enableVersioning) (though [GetObject](https://docs.minio.io/docs/java-client-api-reference.html#getObject) appears not to - maybe I misunderstand)

Please add support for obkect versioning in the .Net Client library.
If there is a plan to, what is the ETA?

thanks

**Comment by kannappanr** [comment]
@Mattacks We will be starting on adding support for Versioning soon. I don't have a timeline yet. Hopefully soon.
