### ISSUE TITLE
differently works in `minio-go` and `minio-dotnet`

### ISSUE THREAD

**Issue by gnh1201** [minio/minio-dotnet#452]
I implemented my program with `minio-go` and `minio-dotnet`, and confirmed that it works well with `minio-go`.

But `minio-dotnet` is something weird...

minio-go (it does works):

```
    // Initialize minio client object.
    minioClient, err := minio.New(endpoint, &minio.Options{
        Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
        Secure: useSSL,
    })
    if err != nil {
        log.Fatalln(err)
    }
```

minio-dotnet (it does not work - infinitely wait):

```
                minio = new MinioClient(endpoint, accessKey, secretKey).WithSSL();
```

What is difference? I tested this in the same computer.

## Files
- minio-test.go : https://gist.github.com/gnh1201/13db1e02c60b7c984ec4406906b71a48
- minio-test.cs : https://gist.github.com/gnh1201/ef2b2b7d7550be2ef6c09a4560077af7

**Comment by phucduong86** [comment]
I am experiencing the same issue.
I needed to specify "us-east-1" as region argument to be able to connect to our server. However, now I get access denied even with our admin account trying to get a test file:
```
Error occurred: Minio.Exceptions.AccessDeniedException: MinIO API responded with message=Access denied on the resource: testbucket/test.pdf
   at Minio.MinioClient.ParseWellKnownErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 452
```

Go client and Javascript client both works fine, only DotNet client failed.

Dotnet:
```
var minio = new MinioClient(endpoint, accessKey, secretKey, "us-east-1").WithSSL();
```

Javascript:
```
minioClient = new Minio.Client({
    endPoint: [blanked],
    port: 443,
    useSSL: true,
    accessKey: '[blanked]',
    secretKey: '[blanked]'
});
```

Go

```
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
```

**Comment by poornas** [comment]
@gnh1201 ,ListBucketsAsync is an asynchronous call and cannot be used in a static method (GetMinio in your gist) without await or .Wait. If you remove that call, it will work as expected.
