### ISSUE TITLE
.net client metaData in PutObjectAsync allow only ascii simbols

### ISSUE THREAD

**Issue by borgez** [minio/minio-dotnet#455]
metaData in PutObjectAsync allow only ascii simbols

```
public class MinioClientTests
	{
		private MinioClient _minio;

		[SetUp]
		public void Setup()
		{
			_minio = new MinioClient("localhost:9000",
				"AKIAIOSFODNN7EXAMPLE",
				"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
			);

			_minio.SetTraceOn();
		}

		[Test]
		public async Task PutObjectAsync_ShouldSaveFile_Test()
		{
			var metaData = new Dictionary<string, string>
			{
				{ "test", "кенгш" }
			};

			await _minio.PutObjectAsync("test", "test_acii", new MemoryStream(new byte[1]), 1, metaData: metaData);
		}
	}
```

> Tests.MinioClientTests.PutObjectAsync_ShouldSaveFile_Test

> Minio.Exceptions.ConnectionException : MinIO API responded with message=Connection error: Request headers must contain only ASCII characters.. Status ...
> 
> Minio.Exceptions.ConnectionException : MinIO API responded with message=Connection error: Request headers must contain only ASCII characters.. Status code=0, response=Request headers must contain only ASCII characters., content=
>    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 447
>    at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 431
>    at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 83
>    at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 605
>    at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 405
>    at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 532
>    at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 301
>    at Tests.MinioClientTests.PutObjectAsync_ShouldSaveFile_Test() in 
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 
> 
> -----
> 
> One or more child tests had errors
>   Exception doesn't have a stacktrace
> 
> 
> 
> Full URL of Request http://localhost:9000/test?location=
> Request completed in 388,9952 ms
> 
> - - - - - - - - - - BEGIN REQUEST - - - - - - - - - -
> 
> GET http://localhost:9000/test?location= HTTP/1.1
> Host: localhost:9000
> location: 
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> x-amz-date: 20200905T130902Z
> Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20200905/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1f2fbfa646f492d674396af4cea1f2936834cd3792496ec2ec891c7090b720ea
> 
> 
> - - - - - - - - - - END REQUEST - - - - - - - - - -
> 
> - - - - - - - - - - BEGIN RESPONSE - - - - - - - - - -
> 
> HTTP/1.1 200 OK
> Accept-Ranges: bytes
> Content-Security-Policy: block-all-mixed-content
> Server: MinIO/RELEASE.2020-08-26T00-00-49Z
> Vary: Origin
> X-Amz-Request-Id: 1631E53142351C7C
> X-Xss-Protection: 1; mode=block
> Date: Sat, 05 Sep 2020 13:09:02 GMT
> Content-Length: 128
> Content-Type: application/xml
> 
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
> 
> - - - - - - - - - - END RESPONSE - - - - - - - - - -
> 
> Full URL of Request http://localhost:9000/test/test_acii
> Request completed in 26,8765 ms
> 
> - - - - - - - - - - BEGIN REQUEST - - - - - - - - - -
> 
> PUT http://localhost:9000/test/test_acii HTTP/1.1
> Host: localhost:9000
> application/octet-stream: System.Byte[]
> x-amz-meta-test: кенгш
> Content-Type: application/octet-stream
> x-amz-content-sha256: 6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d
> x-amz-date: 20200905T130902Z
> Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20200905/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-meta-test, Signature=6a7c3095ee4ab2ef33a728381915d6c011905a34685a095917047a5e25f0b759
> 
> 
> - - - - - - - - - - END REQUEST - - - - - - - - - -
> 
> - - - - - - - - - - BEGIN RESPONSE - - - - - - - - - -
> 
> HTTP/1.1 0 0
> 
> 
> 
> Request headers must contain only ASCII characters.
> - - - - - - - - - - END RESPONSE - - - - - - - - - -
>

**Comment by harshavardhana** [comment]
This seems to be only implemented recently https://github.com/dotnet/runtime/pull/39468

**Comment by harshavardhana** [comment]
Please upgrade to the latest release and latest .net SDK

**Comment by paymansh1992** [comment]
I upgrade to the latest release and latest .net SDK but it didn't work

**Comment by pauuser** [comment]
Still getting the same problem on .NET 8. Please re-open the issue!

**Comment by xibaoning** [comment]
Still getting the same problem on .NET 8. Please re-open the issue!
