### ISSUE TITLE
GetObjectAsync Timeout issue

### ISSUE THREAD

**Issue by Rajeshrg55** [minio/minio-dotnet#456]
I'm using the below code to download the object from minio.

                   MemoryStream memStream = new MemoryStream();
                    string[] filename = URL.Split('/');
                    var _containerName = filename[filename.Length - 2];
                    System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls |
                   System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
                    var minioClient = new MinioClient(minioEndpoint, minioAccessKey, minioSecretKey).WithSSL();

                    minioClient.StatObjectAsync(_containerName, filename[4]);
                    await minioClient.GetObjectAsync(_containerName, filename[4], s => s.CopyTo(memStream));
                    return memStream;

Which is working fine in my BO project but not in DAL project.

The issue is : GetObjectAsync request getting timeout while downloading the object

The SDKs I'm using in the both projects are :
1. Minio Version 3.1.10
2. RestSharp Version 106.3.1

**Comment by poornas** [comment]
For one, you are not awaiting the StatObjectAsync call. Can you share a whittled down sample of your failing project - you can also set minioClient.SetTraceOn() on the client side and if your endpoint is MinIO , then set `mc admin trace -v myminio` to see the requests received by the server and response to isolate the bug in your code.

**Comment by poornas** [comment]
you may also want to check if you need a ConfigureAwait(false) in your application while waiting on the GetObjectAsync
