### ISSUE TITLE
Asp.Net Core DI integration

### ISSUE THREAD

**Issue by sergeyshaykhullin** [minio/minio-dotnet#465]
Any plans to support `Microsoft.Extensions.DependencyInjection`?

**Comment by kannappanr** [comment]
@sergeyshaykhullin We do not have any plans right now.

**Comment by sergeyshaykhullin** [comment]
@kannappanr I can create draft version
You have no plans because of free time or it is sticking on concrete di container?

**Comment by sergeyshaykhullin** [comment]
Hmm...

**Comment by sergeyshaykhullin** [comment]
I created repo and package for Minio integration:
https://github.com/appany/Minio.AspNetCore
https://www.nuget.org/packages/Minio.AspNetCore

Feel free to mention me if you want to migrate it to main repo or to free Minio.AspNetCore package name for your implementation in a future

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
