### ISSUE TITLE
Impossible to connect to host with a specific path (sub.domain.com/minio)

### ISSUE THREAD

**Issue by sristagno** [minio/minio-dotnet#469]
We deployed a minio service that is available in the following address `https://sub.domain.com/minio` and we would be able to access it using the .NET library, but it is only possible to specify a hostname and not an endpoint containing path.

Am I missing something, is there any solution to make this connection?

Thanks

**Comment by vadmeste** [comment]
> https://sub.domain.com/minio

This style is not supported in S3 specification. You need another sub-domain, for example: s3.sub.domain.com/
