### ISSUE TITLE
ListObjectArgs does not exist in v3.1.13

### ISSUE THREAD

**Issue by sebastianbk** [minio/minio-dotnet#483]
According to the [documentation](https://docs.min.io/docs/dotnet-client-api-reference.html), the `ListObjectsAsync` API should take a `ListObjectArgs` object as its only parameter. However, that is not the case. The signature of `ListObjectsAsync` is:

```
public IObservable<Item> ListObjectsAsync(string bucketName, string prefix = null, bool recursive = false, CancellationToken cancellationToken = default);
```

I'm interested in making use of the `start_after` parameter, which is available in the [Python SDK](https://docs.min.io/docs/python-client-api-reference.html). Would this be possible with the `ListObjectArgs` object? Also, what do I need to do in order to get the latest version of the SDK that matches the documentation?

**Comment by sebastianbk** [comment]
I just noticed that the code on GitHub doesn't even align with the documentation. So what's released, what's on GitHub, and what's written in the documentation are three completely different things.

**Comment by harshavardhana** [comment]
> I just noticed that the code on GitHub doesn't even align with the documentation. So what's released, what's on GitHub, and what's written in the documentation are three completely different things.

The github branch will move to release to point to latest releases - things available in the master are not released yet.

**Comment by harshavardhana** [comment]
and the docs is pointing to release branch https://docs.min.io/docs/dotnet-client-api-reference.html#listObjects
