### ISSUE TITLE
MinioClient.ListObjectsAsync() throws an error when the bucket is empty

### ISSUE THREAD

**Issue by Maximkaaa** [minio/minio-dotnet#488]
As the title says, simple code:
```
            try
            {
                await this.client.ListObjectsAsync(bucketName);
                return true;
            }
            catch
            {
                return false;
            }
```
always returns false, when the requested bucket does not contain any objects (e.g. new bucket).

The caught exception is:
```
System.InvalidOperationException: Sequence contains no elements.
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 361
```

**Comment by BigUstad** [comment]
@Maximkaaa Can you please let us know what version of the code are you using? In both the latest from release branch & from master branch, I'm not seeing this error either on Windows or Mac Operating Systems.

**Comment by Maximkaaa** [comment]
I am using version 3.1.13 from Nuget on Linux (Mint 19). I also updated Minio to the latest release. But the same issue is exists when running with other S3 implementations (Yandex in my case).

I've created a simple repro: https://github.com/Maximkaaa/minio-dotnet-bug .

**Comment by BigUstad** [comment]
I've replicated this bug and also debugged it a bit. We'll update you with a solution soon. Thank you for providing us the repro.

**Comment by BigUstad** [comment]
Having await on a function that is not marked async and returns IObservable may be causing an unintended error. Can you please remove the await keyword for ListObjectsAsync & try.

**Comment by BigUstad** [comment]
@Maximkaaa A fix for this issue has been merged into the master. Please try with the master branch. The release will be next.

**Comment by BigUstad** [comment]
Fix 527 merged to master branch.
