### ISSUE TITLE
For unauthenticated requests with listBuckets() -  S3 sends a http.StatusTemporaryRedirect

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-dotnet#5]
https://github.com/minio/minio-dotnet/blob/master/Minio.Client/ObjectStorageClient.cs#L263

Handle the case where un-authenticated requests haveTemporaryRedirect with no parseable error respone, unless ParseError already handles non xml response bodies internally.

**Comment by fkautz** [comment]
ListBuckets is a special case, we'll handle 307 as an auth failure.
