### ISSUE TITLE
How to identify a Directory ??

### ISSUE THREAD

**Issue by oscarpires** [minio/minio-dotnet#502]
I would like to know and understand how Minio can identify in S3Objects dir.
I have a project using AWS S3 C# API and I can continue with that, but identify dir/file its very important for me.

thanks any help!

`var items = client.ListObjects("bucket");

foreach (Item item in items)
{
    if (item.IsDir)
    {
       Console.Out.WriteLine("{0}", item.Key);
     }
}`

**Comment by kannappanr** [comment]
@oscarpires if you look at https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html
The prefixes that are under commonprefixes are considered a directory. Usually, this is filled only when a delimiter is passed.
Closing this issue as answered. Please feel free to reach out to us if you have any further questions.
