### ISSUE TITLE
Is MinioClient thread safe

### ISSUE THREAD

**Issue by FIVIL** [minio/minio-dotnet#526]
Hi, I've seen this question has been asked for java client and go client, however, I couldn't find any conclusive answer about the .NET client so I was wondering is the .NET MinioClient thread-safe?

I am trying to use MinioClient in an asp.net core application and I am creating a singleton service that incorporates a MinioClient object and I keep reusing it, I was wondering whether this is correct behavior or I should instantiate a new MinioClient for every request.

**Comment by kannappanr** [comment]
@FIVIL You should be able to use one client for every bucket.

**Comment by harshavardhana** [comment]
MinIO .NET SDK is thread safe, **Please upgrade to the latest release**
