### ISSUE TITLE
Use with Amazon SDK

### ISSUE THREAD

**Issue by bencyoung-Fignum** [minio/minio-dotnet#544]
Sorry if there's not a better place for this!

I'm attempting to follow https://docs.min.io/docs/how-to-use-aws-sdk-for-net-with-minio-server.html but it doesn't appear to work. Setting the ServiceURL clears the RegionEndpoint and vis-versa. 

Looking at https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L176 it looks like it's been changed so that setting either resets the other.

Is there any way around this? I'm using Minio for local dev and S3 for production storage. Is it better to use the Minio API and use that in production to talk to S3? Are there any docs on doing that?

Thanks,
Ben

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
