### ISSUE TITLE
GetObjectAsync object stream couldn't use on the new FileStreamResult

### ISSUE THREAD

**Issue by onurbos** [minio/minio-dotnet#554]
I try use  GetObjectAsync (Downloads an object as a stream.) and I would like to use stream on FileStreamResult. I can set it but when GetObjectAsync  method finish my FileStreamResult.FileStream contentbytes go 0. You can follow the attaches. 
 GetObjectAsync  hasn't a return type.

My old response and return value with S3.Model 
````
            var file = await _storage.Download(bucket, key);

            var result  = new FileStreamResult(file.ResponseStream, file.Headers.ContentType)
            {
                FileDownloadName = temp.Name + type,
                LastModified = file.LastModified,
                EntityTag = new EntityTagHeaderValue(file.ETag)
            };
````

MinioClient

When I use with this code, i get that

`ObjectDisposedException: Cannot access a closed Stream.`

````
            using (Stream strm = new MemoryStream())
            {
                await _storage.Client1.GetObjectAsync(bucket, key, async stream => { await stream.CopyToAsync(strm); });
              
                fileStreamResult = new FileStreamResult(strm, file.Headers.ContentType)
                {
                    FileDownloadName = temp.Name + type,
                    LastModified = DateTimeOffset.Now,
                    EntityTag = new EntityTagHeaderValue(file.ETag)
                };     
           
                return fileStreamResult;
            }
````

then i try to it with this code, 

````     FileStreamResult fileStreamResult = null;

           await _storage.Client1.GetObjectAsync(bucket, key, stream =>
           {
               fileStreamResult = new FileStreamResult(stream, file.Headers.ContentType)
               {
                   FileDownloadName = temp.Name + type,
                   LastModified = DateTimeOffset.Now,
                   EntityTag = new EntityTagHeaderValue(file.ETag)
               };
           });
            
            return fileStreamResult;
````

It sets to file stream and when finish the GetObjectAsync method, it set to fileStreamResult.FileStream contentBytes as 0 automaticly.

How i can fix this.

Thank you.

![1](https://user-images.githubusercontent.com/29005455/127978902-9227a4f0-0960-4d71-922a-0bcabc8f363f.png)
![2](https://user-images.githubusercontent.com/29005455/127978908-95b97756-5850-44a2-91b7-fef957805d61.png)
![Void](https://user-images.githubusercontent.com/29005455/127978909-955d07b3-2127-43dd-950b-54ed6fc9e425.png)

**Comment by onurbos** [comment]
I have found a solution like that, but i need contentType as dynamically.  I have written as static value ("application/octet-stream"), how to i get that as dynamically.

```
               FileStreamResult fileStreamResult = null;

                await _minioClient.GetObjectAsync(bucket, key, async stream =>
                {
                    using (var ms = new MemoryStream()) {
                   
                        await stream.CopyToAsync(ms);
                 
                        fileStreamResult = new FileStreamResult(new MemoryStream(ms.ToArray()), "application/octet-stream")
                        {
                            FileDownloadName = fileName,
                        };
                    }
                });
                
                return fileStreamResult;
```

**Comment by hyfree** [comment]
The biggest problem with minio is that it cannot handle huge file downloads (file>1GB or file>100GB) and cannot use streaming. When I use asp.net core, minio will eat my memory. you can use
stream.CopyToAsync(ms), but when minio calls back, the user response stream has ended, and the http channel has been closed.
Of course I can use threads or other methods, but there are memory issues and the code is not pretty.
I hope that minio can directly return to the stream and let me close it. If I don't close it, no one can close it.
Or give me an example that allows me to deal with large files very easily.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.

**Comment by ebozduman** [comment]
>you can use
stream.CopyToAsync(ms), but when minio calls back, the user response stream has ended, and the http channel has been closed.

 @hyfree,
The issue was with the async lambda function (`Action<Stream>`) used in `GetObjectAsync` callback function.
So, `Func<Stream, CancellationToken, Task>` support is added to properly await async methods, like `Stream`'s `CopyToAsync`.

@onurbos, @hyfree,
Please follow PR#730, which is currently in the code review process.
The fix will be available as soon as the PR is merged and a new MinIO release is created for `nuget.org`. 
I anticipate it'll be available in the next couple of weeks.
