### ISSUE TITLE
ListenBucketNotifications notifications arrive slow

### ISSUE THREAD

**Issue by slubos** [minio/minio-dotnet#559]
I implemented the `ListenBucketNotifications` method according to the example in the repository (https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/ListenBucketNotifications.cs). 

Trying it in code, I noticed that the notifications for newly created object arrive very late most of the time (after 3-5min), as if there were only sent in some interval. 

I'm not quite sure if I'm missing some configuration in the implementation. I expected the events to appear shortly after the objects have been created.

The problem appears with the Nuget package version 3.1.13.

**Comment by nzsb** [comment]
Same here with 3.1.13, sometimes it takes up 10 minutes, sometimes it comes immediately. When using CLI mc watch, notifications are coming immediately.

After debugging a bit, I noticed that if I fire the exact same request which the library also fires from the same machine with curl, the notification is immediately returned from the server, so this seems to be a problem on the client side.

When debugging, the code is blocked at method ReadLine() in method ListenBucketNotificationsAsync, apparently no line is available from the stream, even if a file is changed on the server.

Then I tried firing a parameterized HttpWebRequest in C# with the same parameters (so no RestSharp like in the library), but without using GzipStream, and the data is instantly available. If I use a GzipStream, it is the same problem, it blocks on the ReadLine for a longer time. So I suspect some problem around GzipStream, but I did not investigate it further, setting AutomaticDecompression to None solved the issue for me, but it needs a change in the library, like this

```
restClient.ConfigureWebRequest(h =>
                            {
                                h.AutomaticDecompression = DecompressionMethods.None;
                            });
```

Also, parameter "suffix" is being passed as "sufffix", this might also worth looking at, this is probably broken.
This is an essential feature which does not work, please provide a solution.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
