### ISSUE TITLE
Releases - Branch and NuGet updates

### ISSUE THREAD

**Issue by hkashif** [minio/minio-dotnet#562]
I can successfully run the 3.1.13 minIO client with .net core 2.1. However, for .net core 3.1, I get the following error:

> HTTP/1.1 503 ServiceUnavailable
> Cache-Control: no-cache
> Content-Length: 107
> Content-Type: text/html
> 503 Service Unavailable
> No server is available to handle this request.
> </body></html>

Using the 3.1.14 code from the **release** branch, works successfully with .net core 3.1

1. Is there any reason why a NuGet package has not been created for 3.1.14?
2. Is there any reason for **master** changes not making it to **release** over the past couple of years?

**Comment by Schinkenkoenig** [comment]
Any updates on this? For me, the change with the port removal from the host header when using a default port is necessary so that correct signatures are created.

**Comment by harshavardhana** [comment]
Please upgrade to latest release.
