### ISSUE TITLE
ListObjectsAsync does not work 50% of the time in asynchronous code

### ISSUE THREAD

**Issue by zolotarevandrew** [minio/minio-dotnet#563]
ListObjectsAsync does not work 50% of the time in asynchronous code.

Thas was my method to get list of objects from folder
```
private List<string> GetObjectFiles(string id)
{
    var observable = _client.ListObjectsAsync(_bucketName, id + "/");
    var files = new List<string>();
    try
    {
        var subscription = observable.Subscribe(
            item => { files.Add(item.Key); },
            ex => throw ex);
        observable.Wait();
        subscription.Dispose();
    }
    catch (InvalidOperationException ex)
    {
        if (!ex.Message.Contains("Sequence contains no elements"))
            throw;
    }

    return files;
}
```
I also tried this 
```
private async Task<List<string>> GetObjectFiles(string id)
{
    var observable = _client.ListObjectsAsync(_bucketName, id + "/");
    var files = new List<string>();
    try
    {
        var subscription = observable.Subscribe(
            item => { files.Add(item.Key); },
            ex => throw ex);
        await observable.ToTask();
        subscription.Dispose();
    }
    catch (InvalidOperationException ex)
    {
        if (!ex.Message.Contains("Sequence contains no elements"))
            throw;
    }

    return files;
}
```

But out of 100 or 1000 runs, 30-50% returned an empty list of files

```
 for (int i = 0; i < 100; i++)
            {
                await InScopeAsync(async (scoped) =>
                {
                    var res = await scoped.Provider.GetRequiredService<IFileStorageClient>()
                        .GetObjectFiles("sign-b7f4a21dbd2648fa8b854df98818c41b");
                    Assert.True(res.Count() == 6);
                });    
            }
```

Then I had to go into the source code of the client
I found GetObjectListAsync 
and made this method which just call http method
```
private async Task<List<string>> GetObjectFiles(string id)
        {
            MethodInfo meth = _client.GetType().GetMethod("GetObjectListAsync", BindingFlags.NonPublic | BindingFlags.Instance);
            Task<Tuple<ListBucketResult, List<Item>>> res = (Task<Tuple<ListBucketResult, List<Item>>>)meth.Invoke(_client, new object[] {_bucketName, id + "/", "", null, default(CancellationToken) });
            var res1 = await res;
            return res1.Item2
                .Select( c => c.Key)
                .ToList();
        }
```

Can you make GetObjectListAsync public?
Because i think a lot of developers don't want to use observable, for simple http request

**Comment by angel199321** [comment]
This happened to me too. Any news?

**Comment by zolotarevandrew** [comment]
use this

`private async Task<List<string>> GetObjectFiles(string id)
        {
            MethodInfo meth = _client.GetType().GetMethod("GetObjectListAsync", BindingFlags.NonPublic | BindingFlags.Instance);
            Task<Tuple<ListBucketResult, List<Item>>> res = (Task<Tuple<ListBucketResult, List<Item>>>)meth.Invoke(_client, new object[] {_bucketName, id + "/", "", null, default(CancellationToken) });
            var res1 = await res;
            return res1.Item2
                .Select( c => c.Key)
                .ToList();
        }`



> This happened to me too. Any news?

**Comment by angel199321** [comment]
> use this
> 
> ```
> private async Task<List<string>> GetObjectFiles(string id)
>         {
>             MethodInfo meth = _client.GetType().GetMethod("GetObjectListAsync", BindingFlags.NonPublic | BindingFlags.Instance);
>             Task<Tuple<ListBucketResult, List<Item>>> res = (Task<Tuple<ListBucketResult, List<Item>>>)meth.Invoke(_client, new object[] {_bucketName, id + "/", "", null, default(CancellationToken) });
>             var res1 = await res;
>             return res1.Item2
>                 .Select( c => c.Key)
>                 .ToList();
>         }
> ```
> 
> > This happened to me too. Any news?

Nice! Seem working perfectly now. You save my day.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.

**Comment by nop00** [comment]
I'm running into the same issue, even with the latest release (4.0.7).  

If anyone needs it, here's an updated version of @zolotarevandrew's workaround that works with release 4.0.7:  
```cs
private async Task<List<string>> GetObjectFiles(MinioClient client, string bucket, string prefix) {
	MethodInfo meth = client.GetType().GetMethod("GetObjectListAsync", BindingFlags.NonPublic | BindingFlags.Instance, new Type[] {
		typeof(string),
		typeof(string),
		typeof(string),
		typeof(string),
		typeof(CancellationToken)
	});
	Task<Tuple<ListBucketResult, List<Item>>> res = (Task<Tuple<ListBucketResult, List<Item>>>)meth.Invoke(client, new object[] { bucket, prefix + "/", "", null, default(CancellationToken) });
	var res1 = await res;
	return res1.Item2
		.Select(c => c.Key)
		.ToList();
}
```
