### ISSUE TITLE
The form-data assembled by JavaScript using PresignedPostPolicyAsync reports an error

### ISSUE THREAD

**Issue by rogerhesong** [minio/minio-dotnet#565]
The form-data assembled by JavaScript using PresignedPostPolicyAsync reports an error, prompting the message: An error occurred when parsing the HTTP request POST at &#39;/&#39; Use the official example to also report an error, https://github.com/minio/minio- dotnet/blob/release/Minio.Examples/Cases/PresignedPostPolicy.cs
![image](https://user-images.githubusercontent.com/12381976/145612240-819e5076-a3d7-4258-87de-322f3d59d916.png)

![image](https://user-images.githubusercontent.com/12381976/145612157-6f93f5d6-688b-4e5b-8730-6d0b9b9cabcb.png)

**Comment by harshavardhana** [comment]
Looks like a client issue, specific HTTP POST is not generated.
