### ISSUE TITLE
Authorization header being erroneously added to anonymous requests

### ISSUE THREAD

**Issue by scoliono** [minio/minio-dotnet#567]
I made a MinioClient and tried to PUT a file anonymously as follows:

```cs
var minio = new MinioClient("192.168.7.164:9001", "", "", "us-west-1");
// ...
minio.PutObjectAsync(bucket, outputPath, stream, dataLength).Wait();
```

My bucket has the following policy.
![image](https://user-images.githubusercontent.com/2191476/146281206-77437cec-66da-445a-a773-aa7d7a532cbd.png)

After the Authenticate() method in V4Authenticator runs, these headers are present. Notice the lack of an access key after `Credential=`. ![image](https://user-images.githubusercontent.com/2191476/146280906-29e4d49d-6dc5-4bcd-8f66-c1f34f4c607b.png)

Then, I get this error:
![image](https://user-images.githubusercontent.com/2191476/146282164-cf27433c-c796-441c-9808-267ee774fc6f.png)

I can do the very same PUT request in Postman as long as I omit the Authorization header. The AWS docs imply this is the correct way: "You can create the AmazonS3Client client without providing your security credentials. Requests sent using this client are anonymous requests, without a signature."

While the V4Authenticator does omit some headers if it detects no access key or secret, I believe it should be skipped entirely.

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio-dotnet/pull/551
