### ISSUE TITLE
MinioNotification is not working for large files

### ISSUE THREAD

**Issue by slubos** [minio/minio-dotnet#569]
When receiving a notfication from the `ListenBucketNotifications` (https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/ListenBucketNotifications.cs), the result can not be deserialized to the `MinioNotification` class, if the file size exceeeds 2147483647 bytes. 
The reason is that the `ObjectMeta.Size` (https://github.com/minio/minio-dotnet/blob/release/Minio/DataModel/MinioNotification.cs) property is an integer value and there is an integer overflow.

Please change the variable type to `long`. A file storage should be able to work with files above 2GB.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
