### ISSUE TITLE
WithSSL with optional parameter

### ISSUE THREAD

**Issue by ajakblackgoat** [minio/minio-dotnet#570]
Not really an issue. But would love to have the method WithSSL comes with optional parameter to disable the ssl that was already enabled before.

This feature will come handy in scenario where the endpoint can be accessed in both secured and unsecured. But sometimes, when the secured url became unavailable, we can switch to unsecured endpoint by calling the WithSSL with the parameter to use unsecure Url instead.

As of now, what I do is recreate the MinioClient instance without calling WithSSL which is I think not that efficient.

Suggested WithSSL method with optional parameter:

```
public MinioClient WithSSL(bool disable = false)
        {
            this.Secure = !disable ;
            Uri secureUrl = RequestUtil.MakeTargetURL(this.BaseUrl, this.Secure);
            this.SetTargetURL(secureUrl);
            return this;
        }
```

**Comment by harshavardhana** [comment]
> This feature will come handy in scenario where the endpoint can be accessed in both secured and unsecured. But sometimes, when the secured url became unavailable, we can switch to unsecured endpoint by calling the WithSSL with the parameter to use unsecure Url instead.

That really doesn't make sense why would you wish to use an unsecured endpoint when a secure endpoint is present? - and why would automatically a secured endpoint goes away? while unsecured is somehow accessible? 

The latter scenario doesn't even make sense when is that possible. There is no server that behaves in that manner nor doesn't MinIO.

**Comment by ajakblackgoat** [comment]
During the dev of my project, our minio server are available in via domain and ip. The ssl cert fo course only applies to the domain name, but not by IP address.
Sometimes, we need to switch between domain and ip due to dns server/nginx issues which are beyond our control. or takes time to rectify.
Like I said before, it's a bonus if there is a way to set the internal props of the client instance which has aleady being set to use ssl, to not use ssl without recreating the instance.
The scenario might not applies to you, but that really happen to me, at least.

**Comment by harshavardhana** [comment]
> During the dev of my project, our minio server are available in via domain and ip. The ssl cert fo course only applies to the domain name, but not by IP address.
> Sometimes, we need to switch between domain and ip due to dns server/nginx issues which are beyond our control. or takes time to rectify.
> Like I said before, it's a bonus if there is a way to set the internal props of the client instance which has aleady being set to use ssl, to not use ssl without recreating the instance.
> The scenario might not applies to you, but that really happen to me, at least.

This is very niche requirement and doesn't make sense.

Somehow IP is exposing a MinIO server both on TLS as well as non TLS, for really no good reason.

I am going to close this issue, it's out of scope. Constructors shouldn't be mangled in this manner of mutation.
