### ISSUE TITLE
System.Net.Http.HttpClient?

### ISSUE THREAD

**Issue by ramonesz297** [minio/minio-dotnet#573]
Any plans to use HttpClient instead of RestSharp?

It is critical for my project, to use HttpClient. 

While it is not implemented i have created my own version (with limited functionality, but it is works)

You can check it here - https://github.com/ramonesz297/minio-client

**Comment by helloxubo** [comment]
Yes, It's very important!  
Please suport HttpClient and DI system.

**Comment by punisher1** [comment]
Or RestSharp v107

**Comment by harshavardhana** [comment]
Fixed by #551
