### ISSUE TITLE
 Whether to set content-md5 for  PresignedPutObjectAsync?

### ISSUE THREAD

**Issue by helloxubo** [minio/minio-dotnet#574]
Hello!
    Whether to set content-md5 for  PresignedPutObjectAsync?

    Thinks!

**Comment by ramonesz297** [comment]
@helloxubo  [as per implementation](https://github.com/minio/minio-dotnet/blob/ef75b2fe96840ad48ddbe62ae19d3d31e9f41904/Minio/V4Authenticator.cs#L284)
Minio do not use content-md5 for generating presigned urls.

**Comment by helloxubo** [comment]
> @helloxubo [as per implementation](https://github.com/minio/minio-dotnet/blob/ef75b2fe96840ad48ddbe62ae19d3d31e9f41904/Minio/V4Authenticator.cs#L284) Minio do not use content-md5 for generating presigned urls.

I want to set some properties of the file when I generating presigned urls, and then verify it when I putobjectAsync it?Is there anything I can do?

**Comment by ebozduman** [comment]
@helloxubo,

As @ramonesz297 explained we do not use content-md5 for presigned urls and this is the same for all Minio SDKs and AWS S3. 
We cannnot change this requirement as it will cause incompatibility.
Please close this issue, if you are satisfied with the explanation.
