### ISSUE TITLE
[QUESTION] How can I get object from specified path in bucket?

### ISSUE THREAD

**Issue by tomaszprasolek** [minio/minio-dotnet#575]
I have created bucket, in that bucket I have created a new path. In that path is a file.
How can I get that file?

**Comment by hyfree** [comment]
C#:

objectName=/path/fileName

function:

GetObjectAsync(string bucketName, string objectName, Action callback, ServerSideEncryption sse)

doc:

https://docs.min.io/docs/dotnet-client-api-reference.html#getObject

**Comment by tomaszprasolek** [comment]
Thanks. 
I've tried to get object in similar way, but it did not worked. Now it's working.
