### ISSUE TITLE
BucketExistsAsync: Minio.Exceptions.AccessDeniedException: MinIO API responded with message=Access denied on the resource: /public/

### ISSUE THREAD

**Issue by GalensGan** [minio/minio-dotnet#581]
when I use :
``` c#
var existArg = new BucketExistsArgs().WithBucket("public");
return await _client.BucketExistsAsync(existArg, cancellationToken);
```
to detect the `public` bucket ,
minio returns `Minio.Exceptions.AccessDeniedException: MinIO API responded with message=Access denied on the resource: /public/`, however it get success with the api `ListBucketsAsync()`

I have searched for days，is there some wrong with my codes or settings? 

thanks!

> sdk version: v3.1.13

**Comment by harshavardhana** [comment]
Please upgrade to latest release.
