### ISSUE TITLE
Can't install MinIO Client v. 4.0.0 via NuGet

### ISSUE THREAD

**Issue by modemaizer** [minio/minio-dotnet#585]
Trying to update client from 3.1.13 or to install it and having next trouble in VS:
![image](https://user-images.githubusercontent.com/7851483/156151010-6f7a13d3-5a13-4a28-83d2-5a165a664583.png)

**Comment by modemaizer** [comment]
But using Package Manager Console it installs successfully

**Comment by harshavardhana** [comment]
Please install using package manager console.
