### ISSUE TITLE
System.NotImplementedException in AssumeRoleProvider

### ISSUE THREAD

**Issue by KamenRiderKuuga** [minio/minio-dotnet#588]
When I want to get a temporary credentials, I use the code:

```c#
MinioClient minio = new MinioClient().WithEndpoint("play.min.io")
                                     .WithCredentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
                                     .Build();

var provider = new AssumeRoleProvider<CredentialsProvider>(minio);

var token = await provider.GetCredentialsAsync();
```

But it `throw new System.NotImplementedException()` in the line 99 of the `AssumeRoleProvider` class.
Could you tell me how to get the temporary credentials by this dotnet sdk?

**Comment by harshavardhana** [comment]
This is not implemented yet as per the code.

**Comment by KamenRiderKuuga** [comment]
Thanks, finally did this with S3's API.
