### ISSUE TITLE
minio dotnet getobject error

### ISSUE THREAD

**Issue by cloudsnake** [minio/minio-dotnet#591]
1----
windows server 2019
server 

set MINIO_ROOT_USER=admin
set MINIO_ROOT_PASSWORD=12345678
minio.exe server   --console-address ":9000"  --address ":9090"   d:\minio\dir1 

2----
client
minio net sdk

download file

try
{
	BucketExistsArgs args = new BucketExistsArgs().WithBucket(bucketName);
	bool found = await _minioClient.BucketExistsAsync(args);
	if (found)
	{
		GetObjectArgs getObjectArgs = new GetObjectArgs()
			.WithBucket(bucketName)
			.WithObject(objectName)
			.WithFile(localFile);
		var status = await _minioClient.GetObjectAsync(getObjectArgs).ConfigureAwait(true);
}
catch
{
}
get error：

API: GetObject(bucket=admin, object=8683bed91a60e701ddcd21c2c968e928243df74062dd8012911263caf9ddf69c)
Time: 12:49:37 UTC 03/10/2022
DeploymentID: 54935906-02ef-4702-8cae-856b724d43aa
RequestID: 16DB05E2C23557B8
RemoteHost: 172.16.1.248
Host: 10.168.1.145:9090
Error: Unable to write all the data to client write tcp 10.168.1.145:9090->172.16.1.248:1029: wsasend: An existing connection was forcibly closed by the remote host. (*fmt.wrapError)
       3: cmd\object-handlers.go:530:cmd.objectAPIHandlers.getObjectHandler()
       2: cmd\object-handlers.go:587:cmd.objectAPIHandlers.GetObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
Functional tests all run fine @cloudsnake on windows as well, including GetObject() - looks like you have some networking issues on your setup. 

PTAL

**Comment by leodada** [comment]
@harshavardhana I meet the same issue,with MINIO-DOTNET 3.1.13
This problem happens occasionally。when I try again its ok，can you give
 me some advices?
message:

API: GetObject(bucket=blobdata, object=rt1031/357541815248781061.blob)
Time: 09:15:45 UTC 11/03/2022
DeploymentID: 187adcbf-c3c0-4c67-8af1-17d289bc9295
RequestID: 1724085A1E9644DC
RemoteHost: 10.8.77.35
Host: 10.8.77.113:9000
UserAgent: MinIO (Microsoft Windows NT 6.2.9200.0;x86_64) minio-dotnet/1.0.9
Error: Unable to write all the data to client write tcp 10.8.77.113:9000->10.8.77.35:54263: wsasend: An existing connection was forcibly closed by the remote host. (*fmt.wrapError)
       3: cmd\object-handlers.go:522:cmd.objectAPIHandlers.getObjectHandler()
       2: cmd\object-handlers.go:579:cmd.objectAPIHandlers.GetObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
