### ISSUE TITLE
Full .NET framework support

### ISSUE THREAD

**Issue by olsh** [minio/minio-dotnet#604]
The latest MinIO version 4.0.1 doesn't support the full .NET framework and some other platforms. Now it is targeted only .NET 5, 6
I believe that the support was removed in this PR #597 

It would be nice to add `netstandard2.0` target because .NET full framework is still supported and used in many projects.
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version

**Comment by harshavardhana** [comment]
@olsh we may consider this in the future thanks for opening the issue.

**Comment by ramonesz297** [comment]
@olsh You can take a look at this [repo](https://github.com/ramonesz297/minio-client) as an alternative. It supports netstandard2.0.
