### ISSUE TITLE
GetObjectAsync Unable to download

### ISSUE THREAD

**Issue by zsenmiao** [minio/minio-dotnet#605]
MinIO version 4.0.1 
Server version [RELEASE.2022-03-14T18-25-24Z]
Test platform windows11
```
var minio = new MinioClient()
                    .WithEndpoint("127.0.0.1:9000")
                    .WithCredentials("OPC4QW24VI68GQ12WHRA", "ERna5+bktNqxzxCfCt+g+DgSA1MjXlEWFfIDon6S")
                    .Build();
var getListBuckets = await minio.ListBucketsAsync();
var bucketName = "media";
var objectName = "test.txt";
var filePath = "D:\\test.txt";
var args = new GetObjectArgs().WithBucket(bucketName).WithObject(objectName).WithFile(filePath);
var stat = await minio.GetObjectAsync(args);
```

**Comment by Mushuizz** [comment]
MinIO version 3.1.13
Server version [RELEASE.2022-03-14T18-25-24Z]
Test platform windows11

but version 3.1.13 It's work

```
var minio = new MinioClient("127.0.0.1:9000", "OPC4QW24VI68GQ12WHRA", "ERna5+bktNqxzxCfCt+g+DgSA1MjXlEWFfIDon6S");
var getListBucketsTask = await minio.ListBucketsAsync();
var bucketName = "media";
var objectName = "aspose.txt";
var filePath = "D:\\aspose.txt";
await minio.GetObjectAsync(bucketName, objectName, filePath);
```

**Comment by bartengine27** [comment]
Can confirm on Windows Server 2016 and dotnet 5: 

- 4.0.1: file downloads don't work
- 3.1.13: file downloads work

**Comment by zsenmiao** [comment]
I found some library use this api but they just use GetObjectAsync with stream
They seem to have the same problem

**Comment by zsenmiao** [comment]
> Can confirm on Windows Server 2016 and dotnet 5:
> 
> * 4.0.1: file downloads don't work
> * 3.1.13: file downloads work

i don't have a server and dotnet sdk is net5

**Comment by ebozduman** [comment]
Looking into the issue...

@zsenmiao, @bartengine27,
In the mean time, could you add error messages and the stack trace you see on your console?

**Comment by zsenmiao** [comment]
> Looking into the issue...
> 
> @zsenmiao, @bartengine27, In the mean time, could you copy/paste the error messages and the stack trace you see on your console?

no error 
i debug your source code 
when i use getobj with file the (requestMessageBuilde.ResponseWriter=this.CallBack) is null so when the code runs to ExecuteTaskCoreAsync  （requestMessageBuilder.ResponseWriter != null） Judgment is not established , responseResult data is fetched but not used

**Comment by ebozduman** [comment]
I saw the issue @zsenmiao. 
Working on the fix.

**Comment by hareeshmu** [comment]
When will be the nuget package release with this fix?

**Comment by ebozduman** [comment]
I cannot give a specific date at this point, but we are pretty close making a new release as soon as a couple of PRs are reviewed, finalized and merged into the master branch.
