### ISSUE TITLE
GetObjectAsync WithOffsetAndLength not working for Contabo s3 compatible storage

### ISSUE THREAD

**Issue by Bheam** [minio/minio-dotnet#611]
Seems to be problem with both the server and the client, as I assume the problem is the short-hand byte range minio is using. I can't find anything in AWS documentation that supports this as a valid syntax.

When minio does "Range: bytes=-4", Contabo returns last 4 bytes, while minio expects that a left-out "0" means start from byte 0 and until byte 4, similar to "Range: bytes=0-4"

Suggested fix: always use full range syntax. It's done right on Stat, but not on Get.

**Comment by harshavardhana** [comment]
> When minio does "Range: bytes=-4", Contabo returns last 4 bytes, while minio expects that a left-out "0" means start from byte 0 and until byte 4, similar to "Range: bytes=0-4"

AWS S3 behaves in the manner this SDK is written, please fix Contabo object storage implementation.
