### ISSUE TITLE
PutObjectArgs Finalizer assumes Stream is a FileStream

### ISSUE THREAD

**Issue by calh1578** [minio/minio-dotnet#613]
In attempting to use PutObjectArgs with a FileName and StreamData of type MemoryStream, experienced the following;

>  Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.IO.MemoryStream' to type 'System.IO.FileStream'. at Minio.PutObjectArgs.Finalize() in /root/.q/sources/minio-dotnet/Minio/DataModel/ObjectOperationsArgs.cs:line 2062
 
Using PutObjectArgs

``` csharp
using var dataStream = new MemoryStream(objectBytes);
await objectOperations.PutObjectAsync(
    new PutObjectArgs()
        .WithBucket(bucket)
        .WithFileName(filename)
        .WithStreamData(dataStream)
        .WithObjectSize(objectBytes.Length));
```

This is due to the finalizer for PutObjectArgs in ObjectOperationsArgs.cs assuming if there is a FileName, the Stream is a FileStream, which is invalid in my use case.

Seems like the following could be used instead:

``` csharp
~PutObjectArgs()
{
    if (this.ObjectStreamData != null)
    {
        this.ObjectStreamData.Close();
    }
}
```

**Comment by harshavardhana** [comment]
Feel free to send a PR @calh1578
