### ISSUE TITLE
StatObjectAsync with StatObjectArgs was not added to IObjectOperations

### ISSUE THREAD

**Issue by calh1578** [minio/minio-dotnet#614]
StatObjectAsync with StatObjectArgs  was implemented in [ObjectOperations.cs](https://github.com/minio/minio-dotnet/blob/eb020da83e8be77affb0118ee7613dec9b1c52a9/Minio/ApiEndpoints/ObjectOperations.cs#L116), but was not added to [IObjectOperations.cs.](https://github.com/minio/minio-dotnet/blob/master/Minio/ApiEndpoints/IObjectOperations.cs)  Only the Obsolete StatObjectAsync is available in the Interface.

**Comment by harshavardhana** [comment]
Feel free to send a fix @calh1578
