### ISSUE TITLE
When I upload a file using PutObjectAsync, and the objectname name contains the () symbol, it will prompt "the request signature we calculated does not match the signature you provided"

### ISSUE THREAD

**Issue by rogerhesong** [minio/minio-dotnet#616]
When I upload a file using PutObjectAsync, and the objectName name contains the () symbol, it will prompt "the request signature we calculated does not match the signature you provided"

## Current Behavior
client.PutObjectAsync("miniotest", "exceldown/26424/26424_2_test123_1_1.xlsx", stream, stream.Length, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").GetAwaiter().GetResult();
this is ok .

client.PutObjectAsync("miniotest", "exceldown/26424/26424_2_test(123)_1_1_1.xlsx", stream, stream.Length, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").GetAwaiter().GetResult();
this is not work:the Stream is the same and it is through Aspose Cells. Converted from Workbook，The only difference is (123),it Prompt error：
MinIO API responded with message=The request signature we calculated does not match the signature you provided. Check your key and signing method.

But when I use FileStream to read files locally, it is OK whether the objectName contains parentheses or not

##  Environment
* Version used (RELEASE.2022-03-17T06-34-49Z):
* Server setup and configuration:
* Operating System and version (minio server: Windows server 2019，Minio for PresignedPostPolicyAsync： .NET SDK 3.1.13):

**Comment by harshavardhana** [comment]
Please provide a reproducer @rogerhesong

**Comment by harshavardhana** [comment]
> Please provide a reproducer @rogerhesong

No reproducer so closing, feel free to let us know if this still needs to be fixed.
