### ISSUE TITLE
EmptyBucketOperation exception is internal, why?

### ISSUE THREAD

**Issue by Argald** [minio/minio-dotnet#617]
**EmptyBucketOperation** exception is thrown from **ListObjectAsync** method in BucketOperations. If I understand, that exception describe empty bucket when list operation is used. But how can I catch this exception. Other exceptions are public. First question is why this method throw on empty bucket? Second is if throw, how can I react to this situation. Thanks.

**Comment by devKlausS** [comment]
@Argald I am experiencing the same issue. 

Meanwhile I will used the following workaround
https://calip.io/LhxQF3aS#F4hwX8cu
```csharp
catch (MinioException ex)
{
    if (ex.GetType().FullName == "Minio.EmptyBucketOperation")
        return Enumerable.Empty<Minio.DataModel.Item>();
    throw;
}
```

**Comment by harshavardhana** [comment]
> **EmptyBucketOperation** exception is thrown from **ListObjectAsync** method in BucketOperations. If I understand, that exception describe empty bucket when list operation is used. But how can I catch this exception. Other exceptions are public. First question is why this method throw on empty bucket? Second is if throw, how can I react to this situation. Thanks.

EmptyBucketOperation will be removed, this is a terrible exception.

**Comment by harshavardhana** [comment]
This abomination of an exception is removed from master branch.
