### ISSUE TITLE
Connection error:This instance has already started one or more requests. 

### ISSUE THREAD

**Issue by sprudel79** [minio/minio-dotnet#620]
Hi everyone,
I have just upgraded to Minio Client 4.0.2 (from 3.1.13) and I am running into issues:
In my .NET 6 based service I am creating a new Minio client on scope "request". That means if within one request multiple calls via minio client need to be done it's reusing the same instance.
E.g. I have an endpoint that can be used to upload a file to the storage. Inside that logic I check first if the passed bucket really exists. This is the first operation of Minio  for that request which is working fine.
Once the check is over the file should be uploaded via Minio as a second step. The MinioClient instance has been already initialized at that time so it's reusing the same. This time I get the following exception message:

MinIO API responded with message=Connection error:This instance has already started one or more requests. Properties can only be modified before sending the first request

If I initialize the MinioClient for each operation it will work again but I doubt this is the idea.

Here's my code of the MinioClient init:

```
_client = new MinioClient()
        .WithEndpoint(_storageOptions.Url)
        .WithCredentials(_storageOptions.Access, _storageOptions.Secret)
        .WithRegion(_storageOptions.Region)
        .WithSessionToken(sessionToken)
        .WithRetryPolicy(customPolicy)
        .WithTimeout(_storageOptions.TimeOutInMS);
        
        if (_storageOptions.UseSSL)
        {
           _client = _client.WithSSL();               
        }
  
        _client = _client.Build(); 
```

I have also tried it to pass my own instance of HttpClient via "WithHttpClient" method. But there was no difference in the result.
What's going wrong here? Or do I need to re-init the MinioClient instance with each operation?
Thanks in advance.

**Comment by sprudel79** [comment]
I have figured it out what has caused the exception.
It's because I am setting a Timeout via " .WithTimeout(_storageOptions.TimeOutInMS);"
This timeout is set in the MinioClient here before sending the request:
```
if (requestTimeout > 0)
{
     this.HTTPClient.Timeout = new TimeSpan(0, 0, 0, 0, requestTimeout);
}
```
Since the code sets this every time prior to sending it will fail if the HttpClient is already in use.
I was able to fix this by using "WithHttpClient" again and to set the timeout manually there when I create the HttpClient instead of using  .WithTimeout.

**Comment by harshavardhana** [comment]
@sprudel79 please provide a reproducer we cannot imagine what you are seeing as an issue.

**Comment by sprudel79** [comment]
Hi @harshavardhana,
sure, here's some code to reproduce it:

minio.csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Minio" Version="4.0.2"/>
  </ItemGroup>
</Project>
```

Program.cs

``` cs
using Minio;

string url = "<url>";
string access = "<access>";
string secret = "<secret>";
string region = "<region>"; 

var minio = new MinioClient()
                        .WithEndpoint(url)
                        .WithCredentials(access, secret)
                        .WithRegion(region)
                        .WithTimeout(60000); // if you remove this line, the entire code will work

// First access will work
var result = await minio.ListBucketsAsync();

// Second access will fail with error: 
/*An exception of type 'Minio.Exceptions.ConnectionException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'MinIO API responded with message=Connection error:This instance has already started one or more requests. Properties can only be modified before sending the first request.. Status code=0, response=This instance has already started one or more requests. Properties can only be modified before sending the first request., content='*/
var result2 = await minio.ListBucketsAsync();
```
