### ISSUE TITLE
HttpClient memory leak

### ISSUE THREAD

**Issue by amiru3f** [minio/minio-dotnet#622]
As you know, dotnet HttpClient is being used for a long time. It has some known issues like bad practices in handling cancelationTokens, memory-management, pooling mechanism and reusability. The current implementation of Minio client has an explicit usage of HttpClient in its approach. There is no disposing mechanism and of course modern generation of dotnet HttpClient management like TypeClients and HttpClientFactory are ignored. This can cause memory leak, performance issues and legacy code generation. According to the links bellow I'm going to implement some bunch of code and an example to show how it could be better impl.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0
https://github.com/dotnet/runtime/issues/25197

**Comment by sprudel79** [comment]
Hi @amiru3f,
I totally agree what you've mentioned.
I had already tried to work with HttpClientFactory which helps with the memory managment according to the discussion here:   https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed-between-requests

However when I inject my managed instance via ".WithHttpClient(_httpClient)" to the MinioClient I ended up in the issue I have described in my post at "https://github.com/minio/minio-dotnet/issues/620".
So right now for me the only possibility to work with the MinioClient is unfortunately not to use ".WithHttpClient" which means the underlying HttpClient is created via "this.HTTPClient = new HttpClient();" in the constructor.

**Comment by amiru3f** [comment]
Hi dear @sprudel79, Of course you are right, but using ".WithHttpClient" causes another issue, You miss the reference of HttpClient which was instanciated in the constructor and it should be collected using Garbage collector (and its not optimized).
So we need a mechanism to dispose the httpClients created by minioClient. My pull request fixes this.

**Comment by sprudel79** [comment]
Thanks @amiru3f , looking forward to using your code enhancements in the next release of the dotnet Minio client.

**Comment by harshavardhana** [comment]
Closed by #633
