### ISSUE TITLE
helper/utils.cs UrlEncode have a bug

### ISSUE THREAD

**Issue by fix-world** [minio/minio-dotnet#625]
in this funciton Replace is not work,like 
_Replace("\\!", "%21")_
may be Replace("!", "%21") is right
so the return need rewrite like 

> return Uri.EscapeDataString(input).Replace("!", "%21")
                                             .Replace("\"", "%22")
                                             .Replace("#", "%23")
                                             .Replace("$", "%24")
                                             .Replace("%", "%25")
                                             .Replace("&", "%26")
                                             .Replace("'", "%27")
                                             .Replace("(", "%28")
                                             .Replace(")", "%29")
                                             .Replace("+", "%2B")
                                             .Replace(",", "%2C")
                                             .Replace(":", "%3A")
                                             .Replace(";", "%3B")
                                             .Replace("<", "%3C")
                                             .Replace("=", "%3D")
                                             .Replace(">", "%3E")
                                             .Replace("?", "%3F")
                                             .Replace("@", "%40")
                                             .Replace("[", "%5B")
                                             .Replace("\\", "%5C")
                                             .Replace("]", "%5D")
                                             .Replace("^", "%5E")
                                             .Replace("'", "%60")
                                             .Replace("{", "%7B")
                                             .Replace("|", "%7C")
                                             .Replace("}", "%7D")
                                             .Replace("~", "%7E");

**Comment by harshavardhana** [comment]
Feel free to send a fix @fix-world
