### ISSUE TITLE
MinioClient constructor httpclient is null

### ISSUE THREAD

**Issue by JiashuoLin** [minio/minio-dotnet#628]
add 

httpclient = new httpclient();

 this.HTTPClient.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", this.FullUserAgent);

**Comment by nartalex** [comment]
Can confirm, getting NullReferenceException in MinioClient(string, string, string, string, string) ctor

**Comment by harshavardhana** [comment]
Looks like you are not using the builder class but instead relying on the older obsolete API, please use the builder pattern.

**Comment by nartalex** [comment]
The [doc](https://docs.min.io/docs/dotnet-client-quickstart-guide.html) doesn't provide any examples on the builder class. Please provide an example or update the doc

**Comment by JiashuoLin** [comment]
I used the nuget package 4.0.2 in.NET and did not create the instance as builder.

**Comment by harshavardhana** [comment]
> The [doc](https://docs.min.io/docs/dotnet-client-quickstart-guide.html) doesn't provide any examples on the builder class. Please provide an example or update the doc

https://github.com/minio/minio-dotnet#minio-client-example that's the first example here.

**Comment by JiashuoLin** [comment]
> > The [doc](https://docs.min.io/docs/dotnet-client-quickstart-guide.html) doesn't provide any examples on the builder class. Please provide an example or update the doc
> 
> https://github.com/minio/minio-dotnet#minio-client-example that's the first example here.

There is no update here https://docs.min.io/docs/dotnet-client-api-reference.html

**Comment by harshavardhana** [comment]
> 
> There is no update here https://docs.min.io/docs/dotnet-client-api-reference.html

This has not been deployed as we are going through some internal changes in the docs @JiashuoLin please refer to GitHub docs as well when in doubt.  

You could have done that yourself.

**Comment by JiashuoLin** [comment]
> > There is no update here https://docs.min.io/docs/dotnet-client-api-reference.html
> 
> This has not been deployed as we are going through some internal changes in the docs @JiashuoLin please refer to GitHub docs as well when in doubt.
> 
> You could have done that yourself.

Thank you. Question solved
