### ISSUE TITLE
Region validation issue

### ISSUE THREAD

**Issue by DanielSilvaFignum** [minio/minio-dotnet#630]
Hello!

After upgrading to the version 4.0.2 (from 3.1.13), all my uploads started to fail (in fact, the MinioClient runs the PutObjectAsync without throwing any issue), but I've debugged MinioClient and I found the following response result:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>xxxxxxxxxx.s3.amazonaws.com</Endpoint><Bucket>xxxxxxxxx</Bucket><RequestId>xxxxxxxxxxx</RequestId><HostId>xxxxxxxxxxxxxxxxx</HostId></Error>
```

From the tests I've made, the issue is related to the following validation, since we are using the region "eu-west-2":
```
// Fetch correct region for bucket if this is not a bucket creation
if (!string.IsNullOrEmpty(objectName) && method != HttpMethod.Put)
{
      region = await GetRegion(bucketName).ConfigureAwait(false);
}
```
I understand the comment before the validation, but the validation is affecting PutObjectAsync (PUT with objectName) and ListObjectsAsync (Get without objectName). Probably more methods are affected, I just didn't test them all.

I think it needs a better way to identify when the request is to create a bucket.

Any ideas?

Regards,
Daniel Silva

**Comment by bencyoung-Fignum** [comment]
Note this is connecting to AWS rather than Minio itself!

**Comment by harshavardhana** [comment]
You need to enable GetBucketLocation() API for us to fetch the region for your bucket. If that doesn't happen we fallback to us-east-1

If you know your bucket and have no provisions to give us GetBucketLocation() API access then use WithRegion() in the client constructor.

**Comment by DanielSilvaFignum** [comment]
In fact I'm using .WithRegion, the situation is that the region is being set only for some operations (minio code, not on my side).

As you can see the code that will set the region for the specific operation, has que following condition:

`!string.IsNullOrEmpty(objectName) && method != HttpMethod.Put`

More detail here: [https://github.com/minio/minio-dotnet/blob/master/Minio/MinioClient.cs#L264](https://github.com/minio/minio-dotnet/blob/master/Minio/MinioClient.cs#L264)

This is not correct, since operations like:

- PutObjectAsync (PUT with objectName)
- ListObjectsAsync (Get without objectName)

Will never have the region set for the request.

**Comment by harshavardhana** [comment]
> In fact I'm using .WithRegion, the situation is that the region is being set only for some operations (minio code, not on my side).
> 
> As you can see the code that will set the region for the specific operation, has que following condition:
> 
> `!string.IsNullOrEmpty(objectName) && method != HttpMethod.Put`
> 
> More detail here: https://github.com/minio/minio-dotnet/blob/master/Minio/MinioClient.cs#L264
> 
> This is not correct, since operations like:
> 
> * PutObjectAsync (PUT with objectName)
> * ListObjectsAsync (Get without objectName)
> 
> Will never have the region set for the request.

Then this is our bug.

**Comment by DanielSilvaFignum** [comment]
Hi @harshavardhana, I've tested with the changes from #637 and the problem remains. I've looked at the changes done and it's only related to the user agent, maybe a missing commit?

**Comment by DanielSilvaFignum** [comment]
In the test application that I have, which is the one I'm testing against the minio-dotnet master branch, I'm doing the following:

```
MinioClient minio = new MinioClient()
                        .WithEndpoint(config.Endpoint)
                        .WithCredentials(config.AccessKey, config.SecretKey)
                        .WithRegion(config.Region);

if (config.SSL) minio = minio.WithSSL();

return minio.Build();
```

**Comment by harshavardhana** [comment]
can you enable SetTraceOn

```
minioClient.SetTraceOn(new JsonNetLogger())
```

and share the output?

**Comment by DanielSilvaFignum** [comment]
I'll have to cut some info, to avoid exposure of sensitive data:

This is what we are getting from the ListBucketsAsync:

URL: "https://s3.amazonaws.com:443/"

Response:
<Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'eu-west-2' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region>

The region that we are using is eu-west-2.

Since I have my test project referencing the source code, I've done the following change just to see the behaviour:

```
    internal async Task<HttpRequestMessageBuilder> CreateRequest(
        HttpMethod method,
        string bucketName = null,
        string objectName = null,
        Dictionary<string, string> headerMap = null,
        string contentType = "application/octet-stream",
        byte[] body = null,
        string resourcePath = null)
    {
        var region = Region;    <----- HERE
        if (bucketName != null)
        {
            utils.ValidateBucketName(bucketName);
            // Fetch correct region for bucket if this is not a bucket creation
            if (!string.IsNullOrEmpty(objectName) && method != HttpMethod.Put)
                region = await GetRegion(bucketName).ConfigureAwait(false);
        }
```

I just assigned the Region without any conditions (it's silly, just for testing) and the ListBucketsAsync started to work.

In my modest opinion, I think that the region assignment should be in each operation control, to avoid this generic conditions (having bucket, method != put,...)

**Comment by DanielSilvaFignum** [comment]
Hi @harshavardhana, this issue is still in the last version of minio client, is there any chance of this getting fixed? We would like to upgrade the version, but it's impossible without fixing this issue.

Thanks.
