### ISSUE TITLE
Version 4.0.3 doesn't work with net4.8: Strong name signature could not be verified

### ISSUE THREAD

**Issue by Malgefor** [minio/minio-dotnet#643]
Hi! I am trying to use the 4.0.3 version with net4.8, but on multiple machines (both dev and deployment servers) I am getting an exception when trying to load the assembly that uses the Minio package. See the screenshot below for more information. Last version to work is 3.1.13 (which was also the last version to work with net4.8 if I'm correct).

![image](https://user-images.githubusercontent.com/9074275/169774916-1c356557-ec43-4a71-90dd-1346fc57eb18.png)

**Comment by ebozduman** [comment]
Looking into it...

**Comment by ebozduman** [comment]
@malgefor,

I cannot reproduce your issue on a Windows 11 system.
I did `dotnet clean` (I even ran `dotnet locals all --clear`), and then restore, build and run with net 4.8. 
Everything worked fine, and all of our functional tests passed.

So, we need more information about the reproduction steps.

Please give us more information, like:
How did you get your `Minio.4.0.3.nupkg` package? Did you manually download it? If so, where did you put it?
Please also copy your `*.csproj` file.
I am not sure, if it is going to help or not, but regardless, you can enable assembly bind logging until we are done with debugging.

I labeled the issue as "Works as intended" for now. If the issue can be reproduced, then we can remove the label and set a priority for it.

**Comment by Malgefor** [comment]
Hi @ebozduman,

I got the package via NuGet. We were already using an older version and wanted to upgrade to 4.0.3. I manage the package via Visual Studio and not manually. I did get some more output regarding the assembly binding (see the screenshot below)

The strange thing is: I can also reproduce the issue when creating a fresh ASP.NET MVC project:

- Open Visual Studio
- Create a new `ASP.NET MVC Web Application` targeting .NET 4.8
- Select the MVC template
- Install Minio 4.0.3 via the NuGet browser
- Start/Debug the project
- See the same error I posted before & below

**Other stuff**
- I have cleared the NuGet cache (Tools -> NuGet Package Manager -> Package Manager Settings -> Clear All NuGet Cache(s)) and deleted all bin/obj folders + Cleaned the project. 
- Next to all above, I have verified the NuGet package with nuget.exe, but that says that everything is fine..

![assembly_binding](https://user-images.githubusercontent.com/9074275/169989438-0f8b5186-fee1-4c19-b594-7ad60b6e29fc.png)

**Comment by egorpark777** [comment]
I am seeing the same issue.

**Comment by Malgefor** [comment]
Windows OS version: Microsoft Windows 11 Enterprise - 10.0.22000 Build 22000
Visual-Studio version: 17.2.2
Csproj: the default template from Visual Studio ASP.NET MVC project with only the Minio nuget package installed

**Comment by ebozduman** [comment]
Reproduced and fixes the problem.
