### ISSUE TITLE
Error message in name length checks does not match logic

### ISSUE THREAD

**Issue by pbolduc** [minio/minio-dotnet#645]
There are a number of parameter checks where the length check looks for `> 512` but the error in the exception says 1024. For example

https://github.com/minio/minio-dotnet/blob/bb2d0943552114d37e59bf8194b384aad129d765/Minio/Helper/utils.cs#L78-L79

https://github.com/minio/minio-dotnet/blob/bb2d0943552114d37e59bf8194b384aad129d765/Minio/Helper/utils.cs#L84-L85

**Comment by AdamHodgson** [comment]
Hi pbolduc,

Isn't this just due to the use of UTF-16 encoding? There's a test here which appears to show the correct behaviour.
https://github.com/minio/minio-dotnet/blob/bad67b668de1105de8949283d28d85ea8e2efdb8/Minio.Tests/UtilsTest.cs#L88-L99

**Comment by pbolduc** [comment]
If you are encoding at UTF-16, then each `character` is two bytes. But the error message is saying it cant be more then 1024 `characters`. It would be confusing to a caller when they log the error message any it says more than 1024 `characters` but they have ensured it is less than or equal to 1024 characters. The exception should say `Object name cannot be greater than 512 characters.`

For example...

```cs
    [TestMethod]
    public void TestVeryLongObjectName513()
    {
        try
        {
            var objName = TestHelper.GetRandomName(513); // definately not greater than 1024
            utils.ValidateObjectName(objName);
        }
        catch (InvalidObjectNameException ex)
        {
            Assert.AreEqual(ex.ServerMessage, "Object name cannot be greater than 1024 characters.");
        }
    }
```

**Comment by pbolduc** [comment]
Not sure if Minio is following AWS specifications, but based on 
[Creating object key names](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html), it says: `The object key name is a sequence of Unicode characters with UTF-8 encoding of up to 1,024 bytes long.`.  Just because strings in the runtime are represent as UTF-16, when you serialize the request for the network, it will need to be encoded as UTF-8. So perhaps a better check would be:

```cs
    internal static void ValidateObjectName(string objectName)
    {
        if (string.IsNullOrEmpty(objectName) || objectName.Trim() == string.Empty)
            throw new InvalidObjectNameException(objectName, "Object name cannot be empty.");
        
        if (Encoding.UTF8.GetByteCount(objectName) > 1024)
            throw new InvalidObjectNameException(objectName, "Object name cannot be greater than 1024 characters.");
    }
   ```
