### ISSUE TITLE
Large Object Heap (LOH) issues

### ISSUE THREAD

**Issue by Gounlaf** [minio/minio-dotnet#648]
Hi,

I'm using the sdk in long running project. Memory management is a big topic.

Rider IDE (Jetbrains) is warning me about LOH allocation - in internal method `ReadFullAsync`.

Recommendations are, at least,  to use, `ArrayPool` instead of byte array directly.
Could it be used?
Or even better : stream everywhere

I might help if needed (but I'm not a expert).

Regards.

**Comment by Gounlaf** [comment]
I understand it for the stream. But I don't understand the issue with the `ArrayPool`. Could you explain?

Thanks

**Comment by harshavardhana** [comment]
> I understand it for the stream. But I don't understand the issue with the `ArrayPool`. Could you explain?

An ArrayPool only works when the buffer is constant, if you have variadic buffers that is for different types of objects with different lengths - what good an ArrayPool do?

**Comment by Gounlaf** [comment]
Well, I can only point you to some articles that talk about it.

- https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0#minimize-large-object-allocations
- https://adamsitnik.com/Array-Pool/
- https://blog.randes.me/avoiding-array-pitfalls-in-c-net/
- https://endjin.com/blog/2020/09/arraypool-vs-memorypool-minimizing-allocations-ais-dotnet

Like I said, I'm not an expert at all.

I can only says that I saw significantly memory improvement using `ArrayPool` and [Microsoft.IO.RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) over the time on different projects.

**Comment by Gounlaf** [comment]
About checksum, looking at : https://github.com/minio/minio-dotnet/blob/76bb291246472c16f0dee9eedc1698a2327d9185/Minio/V4Authenticator.cs#L248

[Calculation on stream is possible](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=net-6.0#system-security-cryptography-hashalgorithm-computehash(system-io-stream))

**Comment by edemartel** [comment]
Hashing algorithms are designed to work incrementally by hashing chunks. You don't have to store the entire request in memory to hash it, you can just read some amount in a small buffer, update the hash, read the next block, etc. And, indeed, this is what the `ComputeHash` overload that takes a stream does. With that in mind, you can then use a memory pool to get that small work buffer.

**Comment by Gounlaf** [comment]
Hi,

Anynews regarding this issue?
I can try to contribute.

**Comment by martijn00** [comment]
@ebozduman A lot of work has been done to move everything over to use Span and Memory types. Can you check if this works better now?

**Comment by martijn00** [comment]
@Gounlaf @ebozduman I think this can be closed now

**Comment by ebozduman** [comment]
@Gounlaf 
There are quite a lot of recent changes, which are very soon to arrive in the next release and will affect the memory foot print of MinIO Dotnet SDK.
There will still be room for improvements, but the context will be different as the base code has changed and it could be a good idea to open up a new issue, but ...
@martijn00 
Let's keep this issue open for a couple of weeks after the next release for the community to evaluate the effect of the changes.
Then, we can decide to close it or keep it.

**Comment by martijn00** [comment]
@ebozduman can this be closed now?

**Comment by ebozduman** [comment]
Closed as there were quite a lot of changes done in the way .net SDK memory is managed.
