### ISSUE TITLE
CompleteMultipartUploadAsync can validate the Content -MD5?

### ISSUE THREAD

**Issue by helloxubo** [minio/minio-dotnet#653]
Hello!
I use multipart upload, but I have to make sure the file is valid. 
Can i verified this in the CompleteMultipartUploadAsync method (such as use Content -MD5)? 
Or is there any better way?

Thinks!

**Comment by klauspost** [comment]
Multipart uploads does not calculate the md5, since the S3 API does not do that. This also makes sense since there is no scalable way to do that since parts can come in any order and at the same time.

Each part sends its expected MD5/SHA256 so the file is verified that way by the library.

**Comment by helloxubo** [comment]
> Multipart uploads does not calculate the md5, since the S3 API does not do that. This also makes sense since there is no scalable way to do that since parts can come in any order and at the same time.
> 
> Each part sends its expected MD5/SHA256 so the file is verified that way by the library.

Is there any way to get the  MD5/SHA256 of an object?

**Comment by helloxubo** [comment]
@klauspost  You means that an  object in the bucket have multiple MD5? 
Can uploaded objects also not get MD5?

**Comment by helloxubo** [comment]
@klauspost  Ok, I've learned. 
Thank you very much.
