### ISSUE TITLE
Support Request for s3-zip extension: Headers removed on StatObjectAsync, GetObjectAsync

### ISSUE THREAD

**Issue by mongongo** [minio/minio-dotnet#664]
hi!
i've tried use s3-zip extension and pass x-minio-extract header with GetObjectAsync, but it use inside StatObjectAsync, which cut all my headers.
![image](https://user-images.githubusercontent.com/1768256/179555931-7a0083f7-cf7e-40f5-b5e8-75f4007dd8ef.png)

**Comment by harshavardhana** [comment]
dotnet SDK doesn't support s3-zip extension feature yet @mongongo

**Comment by ebozduman** [comment]
Thanks @mongongo 
We'll treat this issue as a request for support

**Comment by mongongo** [comment]
thank you!

**Comment by ebozduman** [comment]
Fixed by PR#687

**Comment by mongongo** [comment]
hello! Could you tell me in what release is this update scheduled?
