### ISSUE TITLE
Inject Ioc-managed HttpClient for MinioClient via constructor

### ISSUE THREAD

**Issue by Ruthlessist** [minio/minio-dotnet#675]
In version 4.0.4 we had the `MinioClient(HttpClient httpClient)` constructor which unfortunately is now marked obsolete:
* Having this function can easily use `services.AddHttpClient<MinioClient>()` to inject HttpClient.
* The parameterless constructor creates an HttpClient instance. If another httpclient instance is subsequently passed in using the builder mode, we will have a garbage. Maybe we can simply set a switch, e.g. `MinioClient(bool createHttpClient = true)`, to control whether to create in the constructor or not.

**Comment by ebozduman** [comment]
PR #681 only addresses the 2nd bullet in the description of this issue above by cleaning up the previously created HttpClient instance, before creating a new one which happens when `WithHttpClient` or `WithProxy` methods are called.

**Comment by ebozduman** [comment]
The team's decision is to go with builder pattern in methods, and this decision is valid for all MinIO implementations where ever it is applicable.
So, the bottom-line is we cannot revive back the methods, which went into obsolete/deprecated mode for this  reason.
