### ISSUE TITLE
Bug: WithTagging() is ignored for files that are larger than 5MB

### ISSUE THREAD

**Issue by pwiesinger** [minio/minio-dotnet#676]
When uploading a file that has more than 5MB, the tags specified in the WithTagging method are ignored.

Here is an example implementation that causes this problem:

```
await _minioClient.PutObjectAsync(new PutObjectArgs()
            .WithBucket(DefaultBucketName)
            .WithObject(fileId)
            .WithObjectSize(formFile.Length)
            .WithTagging(new Tagging(new Dictionary<string, string>
            {
                {"fileName", "TEST"}
            }, true))
            .WithContentType(formFile.ContentType)
            .WithStreamData(formFile.OpenReadStream()));

```

I suspect the putObjectArgs on line 674 inside ObjectOperation.cs to cause the problem, since the tags are not included here. This would also explain why this only happens to files larger than 5MB.

**Comment by harshavardhana** [comment]
Looks like multipart API doesn't set the relevant tags
