### ISSUE TITLE
How to  dispose "PutObjectArgs" object in .Net SDK

### ISSUE THREAD

**Issue by WeisonCheng** [minio/minio-dotnet#684]
using System.Collections.Generic;
using System.IO;

namespace Minio
{
    public class PutObjectArgs : ObjectWriteArgs<PutObjectArgs>
    {
        public PutObjectArgs();

        ~PutObjectArgs();

        public PutObjectArgs WithFileName(string file);
        public PutObjectArgs WithHeaders(Dictionary<string, string> metaData);
        public PutObjectArgs WithObjectSize(long size);
        public PutObjectArgs WithStreamData(Stream data);
    }
}

**Comment by ebozduman** [comment]
@WeisonCheng 

This is not a bug but a question.
Here is the answer:
 You can always ask questions on Slack.
