### ISSUE TITLE
Configure object tag limits

### ISSUE THREAD

**Issue by poostwoud** [minio/minio-dotnet#700]
Hi,

Currently the number of tags associated with an object is 10. I can find this cap in the client, but is it only a client side cap or is it capped in MinIO itself as well?

Would it be an option to make the tag limits configurable, and therefor knowingly accepting loss of S3 compatibility?

Cheers,

Peter

**Comment by harshavardhana** [comment]
This cannot be changed, and there are no plans to change it @poostwoud - 10 is enough for all practical purposes.
