### ISSUE TITLE
  No return information after uploading

### ISSUE THREAD

**Issue by 604980670** [minio/minio-dotnet#707]
After uploading, there is no return information ObjectStat. VersionId is available only when downloading. Why does Java have return values

**Comment by pbolduc** [comment]
I would agree with @604980670 that not getting the response properties when doing a putobject is limiting. If you bucket has versioning enabled, it is not possible to reliably determine the version id (`x-amz-version-id` header) for the object and version you just uploaded. The type `Minio.PutObjectResponse` should be made public and response headers made available on the response to the API consumers.   If I want to get the `x-amz-version-id`, I can get the value from the header dictionary.

**Comment by pbolduc** [comment]
I think the library should be changed so that all the response types expose the collection of headers from the response. Each response type could add helper properties that pull data from the header collection. By exposing the response headers directly, users can pull out headers that may not have helper properties.

Something like this:

```cs
public class GenericResponse
{
    /// <summary>
    /// The headers from the response.
    /// </summary>
    public IReadOnlyDictionary<string, string> Headers { get; }

    internal GenericResponse(HttpStatusCode statusCode, string responseContent, IReadOnlyDictionary<string, string> headers)
    {
        ResponseContent = responseContent;
        ResponseStatusCode = statusCode;
        Headers = headers;
    }

    internal string ResponseContent { get; }
    internal HttpStatusCode ResponseStatusCode { get; }

    /// <summary>
    /// Gets the header value if it exists, or null if it does not exist.
    /// </summary>
    /// <param name="key"></param>
    /// <returns></returns>
    protected string TryGetStringHeader(string key)
    {
        Headers.TryGetValue(key, out var value);
        return value;
    }
}

internal class PutObjectResponse : GenericResponse
{
    internal string Etag => TryGetStringHeader("Etag");

    internal PutObjectResponse(HttpStatusCode statusCode, string responseContent, IReadOnlyDictionary<string, string> headers)
        : base(statusCode, responseContent, headers)
    {
    }
}
```
