### ISSUE TITLE
IProgress for put object scenario

### ISSUE THREAD

**Issue by Dmitry0108** [minio/minio-dotnet#717]
Please add IProgress for PutObjectAsync with MultipartUpload

**Comment by Kvas007** [comment]
I can do this, if owners create the branch

**Comment by lukashev-di** [comment]
I can do this, if owners create the branch

**Comment by martijn00** [comment]
@ebozduman this can be closed

**Comment by ebozduman** [comment]
Fixed by PR [#723](https://github.com/minio/minio-dotnet/pull/723)
