### ISSUE TITLE
Ssl Validation Callback

### ISSUE THREAD

**Issue by ahmetkoprulu** [minio/minio-dotnet#720]
Hello, I want to implement my SSL validation logic or bypass it. 

Currently, I tried `System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, errors) => true;` but it does not seem working.
Is there any way to achieve this?

Thanks.

**Comment by Sergey-Terekhin** [comment]
Provide custom `HttpClient` to the `MinioClient` with set handler like this:
```c#
new MinioClient().WithHttpClient(HttpClientFactory.Create(new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback = (r, c, ch, policy) => true
                }));
```
And it should work

**Comment by ahmetkoprulu** [comment]
Thank you @Sergey-Terekhin.
