### ISSUE TITLE
Is sig-v4 supported? I use r2 of cloudflare to generate a presignature url with an error.

### ISSUE THREAD

**Issue by bbhxwl** [minio/minio-dotnet#726]
Is sig-v4 supported? I use r2 of cloudflare to generate a presignature url with an error.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/26525599/206912686-3e68aea5-bca8-46bf-ad3f-14156673d543.png">

**Comment by harshavardhana** [comment]
Of course it's supported, you forgot to add x-amz-content-sha256

**Comment by bbhxwl** [comment]
> Of course it's supported, you forgot to add x-amz-content-sha256

I don't know where to add it. Any examples?

**Comment by harshavardhana** [comment]
> > Of course it's supported, you forgot to add x-amz-content-sha256
> 
> I don't know where to add it. Any examples?

Can you share your presigned URL ?

**Comment by bbhxwl** [comment]
> 

https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc

**Comment by bbhxwl** [comment]
> > > Of course it's supported, you forgot to add x-amz-content-sha256
> > 
> > 
> > I don't know where to add it. Any examples?
> 
> Can you share your presigned URL ?

https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc

**Comment by bbhxwl** [comment]
> > > Of course it's supported, you forgot to add x-amz-content-sha256
> > 
> > 
> > I don't know where to add it. Any examples?
> 
> Can you share your presigned URL ?

MinioClient minioClient = new MinioClient().WithEndpoint("url").WithCredentials("*******", "*********").WithSSL().Build();
var model=new PresignedPutObjectArgs().WithHeaders(new Dictionary<string, string>(){{"x-amz-content-sha256",HttpUtility.UrlEncode("UNSIGNED-PAYLOAD")}})
    .WithExpiry(60000).WithBucket("bbhxwl").WithObject("test.txt");
var rs=await minioClient.PresignedPutObjectAsync(model);

**Comment by harshavardhana** [comment]
> > > > Of course it's supported, you forgot to add x-amz-content-sha256
> > > 
> > > 
> > > I don't know where to add it. Any examples?
> > 
> > 
> > Can you share your presigned URL ?
> 
> https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc

So there is an implementation issue in CloudFlare the x-amz-content-sha256 is already present in query param. They are expecting this to be part of HTTP header as well.

This in an AWS S3 incompatible implementation, CloudFlare should fix this on their end. This is not an issue this SDK.

**Comment by bbhxwl** [comment]
> > > > > Of course it's supported, you forgot to add x-amz-content-sha256
> > > > 
> > > > 
> > > > I don't know where to add it. Any examples?
> > > 
> > > 
> > > Can you share your presigned URL ?
> > 
> > 
> > https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc
> 
> So there is an implementation issue in CloudFlare the x-amz-content-sha256 is already present in query param. They are expecting this to be part of HTTP header as well.
> 
> This in an AWS S3 incompatible implementation, CloudFlare should fix this on their end. This is not an issue this SDK.

![image](https://user-images.githubusercontent.com/26525599/206967685-70f526b9-3bb1-4898-a310-87062bc92b38.png)
![image](https://user-images.githubusercontent.com/26525599/206967719-91a8b8d0-5048-490b-b6e6-006b1be984aa.png)

**Comment by bbhxwl** [comment]
> > > > > Of course it's supported, you forgot to add x-amz-content-sha256
> > > > 
> > > > 
> > > > I don't know where to add it. Any examples?
> > > 
> > > 
> > > Can you share your presigned URL ?
> > 
> > 
> > https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc
> 
> So there is an implementation issue in CloudFlare the x-amz-content-sha256 is already present in query param. They are expecting this to be part of HTTP header as well.
> 
> This in an AWS S3 incompatible implementation, CloudFlare should fix this on their end. This is not an issue this SDK.

I quoted all the header information without success.

**Comment by harshavardhana** [comment]
> > > > > > Of course it's supported, you forgot to add x-amz-content-sha256
> > > > > 
> > > > > 
> > > > > I don't know where to add it. Any examples?
> > > > 
> > > > 
> > > > Can you share your presigned URL ?
> > > 
> > > 
> > > https://1f1e8771d43fdecca0a35a9fa08c1e63.r2.cloudflarestorage.com/bbhxwl/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=867e3576166dab66ec1a3090344fb8ca%2F20221212%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221212T052145Z&X-Amz-Expires=60000&X-Amz-SignedHeaders=host&x-amz-content-sha256=UNSIGNED-PAYLOAD&X-Amz-Signature=ec2f35d6840c680fdf7ab4b830980b279d0a59929113c56a4872afa868e7dbdc
> > 
> > 
> > So there is an implementation issue in CloudFlare the x-amz-content-sha256 is already present in query param. They are expecting this to be part of HTTP header as well.
> > This in an AWS S3 incompatible implementation, CloudFlare should fix this on their end. This is not an issue this SDK.
> 
> I quoted all the header information without success.

There are more problems - looks like they do not support pre-signed URLs properly. Even `x-amz-algorithm` is ignored in the query URL.

**Comment by harshavardhana** [comment]
Please ask Cloudflare @bbhxwl or use a proper AWS S3-compatible vendor.
