### ISSUE TITLE
get file data  without downloading

### ISSUE THREAD

**Issue by vlapenkov** [minio/minio-dotnet#733]
Hello.
Is there way to get file data without downloading it?
You have example of getting file  https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/GetObject.cs
which means, file is downloaded locally. 
Thanks in advance.

**Comment by warappa** [comment]
Hi @vlapenkov,
I use `ListObjectsAsync` with `WithPrefix(<objectkey>)`.

```csharp
public async Task<Item?> GetObjectInfoAsync(string bucketName, string objectKey)
{
    var args = new ListObjectsArgs()
        .WithBucket(bucketName)
        .WithPrefix(objectKey);

    var observable = _client.ListObjectsAsync(args);

    using var subscription = observable
        .Where(item => !item.IsDir && string.Equals(item.Key, objectKey, StringComparison.Ordinal))
        .Subscribe();

    return await observable
        .FirstOrDefaultAsync();
}
```

Disclaimer: I'm also new to this 😉

**Comment by martijn00** [comment]
@ebozduman can this be closed as an answer is provided in the comment?

**Comment by ebozduman** [comment]
@vlapenkov ,

You can use [mc stat](https://min.io/docs/minio/linux/reference/minio-mc/mc-stat.html#command-mc.stat) command, which displays information on objects in a MinIO bucket, including object metadata.
