### ISSUE TITLE
MinIO Client does not support XML content parsing when namespace not stated in the content

### ISSUE THREAD

**Issue by tpatersonRBR** [minio/minio-dotnet#761]
The System.Xml.Serialization.XmlSerializer used in numerous places across the client does not support parsing of xml content that doesn't specify a namespace.

For example, the following xml causes an exception:
```
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<ListBucketResult>
  <Name>cs-redbox</Name>
  <Prefix>6a0313c3-4694-4408-a031-b32508220019/</Prefix>
  <IsTruncated>false</IsTruncated>
  <KeyCount>2</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <Delimiter>/</Delimiter>
  <Contents>
    <Key>6a0313c3-4694-4408-a031-b32508220019/6a0313c3-4694-4408-a031-b32508220019.wav</Key>
    <LastModified>2023-03-29T05:22:14.000Z</LastModified>
    <ETag>&quot;00000001c9dc174964240346160d7a30&quot;</ETag>
    <Size>384622</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Contents>
    <Key>6a0313c3-4694-4408-a031-b32508220019/6a0313c3-4694-4408-a031-b32508220019_participant_0.raw</Key>
    <LastModified>2023-03-24T12:26:46.000Z</LastModified>
    <ETag>&quot;00000001c8e14745641dcf4627933da8&quot;</ETag>
    <Size>108241</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>
```

When passed as the responseContent parameter in the GetObjectsListResponse constructor, the XmlSerializer throws an exception during deserialization:
https://github.com/minio/minio-dotnet/blob/master/Minio/DataModel/BucketOperationsReponse.cs#:~:text=internal%20class%20GetObjectsListResponse%20%3A%20GenericResponse
```
        using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(responseContent)))
        {
            BucketResult = (ListBucketResult)new XmlSerializer(typeof(ListBucketResult)).Deserialize(stream);
        }
```
System.InvalidOperationException: 'There is an error in XML document (2, 2).'
InnerException: System.InvalidOperationException: '<<ListBucketResult xmlns=''>ListBucketResult xmlns=''> was not expected.'

There are several solutions posted online using an XmlTextReader instead of the XmlSerializer:

- https://stackoverflow.com/questions/2296305/deserialize-xml-without-namespaces-but-in-a-class-expecting-namespaces
- https://stackoverflow.com/questions/870293/can-i-make-xmlserializer-ignore-the-namespace-on-deserialization

**Comment by tpatersonRBR** [comment]
There is also a separate issue with the XDocument parsing requiring the namespace to be present to be able to extract the "Descendants":
```
        var root = XDocument.Parse(responseContent);
        var items = from c in root.Root.Descendants("{http://s3.amazonaws.com/doc/2006-03-01/}Contents")
            select new Item
            {
                Key = c.Element("{http://s3.amazonaws.com/doc/2006-03-01/}Key").Value,
                LastModified = c.Element("{http://s3.amazonaws.com/doc/2006-03-01/}LastModified").Value,
                ETag = c.Element("{http://s3.amazonaws.com/doc/2006-03-01/}ETag").Value,
                Size = ulong.Parse(c.Element("{http://s3.amazonaws.com/doc/2006-03-01/}Size").Value,
                    CultureInfo.CurrentCulture),
                IsDir = false
            };
```

**Comment by tpatersonRBR** [comment]
I have fixed this issue in this PR:
https://github.com/minio/minio-dotnet/pull/762

**Comment by martijn00** [comment]
@ebozduman this can be closed now.

**Comment by ebozduman** [comment]
PR #762 and PR #763 fixed this issue.
