### ISSUE TITLE
Strong name error

### ISSUE THREAD

**Issue by vartald** [minio/minio-dotnet#768]
Hi!
I tried to use the latest version of the dll (4.0.7) in my project written in asp.net ( framework 4.8 ) but when I start the minio dll it doesn't have a strong name.
The error it gives me on startup is the following: _The file or assembly 'Minio' or one of its dependencies could not be loaded. Strong name signature verification failed. The assembly may have been tampered with or delayed signed, but is only partially signed with the correct private key. (Exception from HRESULT: 0x80131045)_

If I download the project and recompile it directly adding the dll instead it works correctly.
Is it possible to have the correctly signed version on nuget?

Thank you!

**Comment by martijn00** [comment]
@ebozduman same as https://github.com/minio/minio-dotnet/issues/661
Is fixed in the next version

**Comment by martijn00** [comment]
@ebozduman this can be closed

**Comment by ebozduman** [comment]
PR #776 fixes this issue.
Closing...
