### ISSUE TITLE
Minio Sdk not work for old asp.net mvc5

### ISSUE THREAD

**Issue by lujamaharjan** [minio/minio-dotnet#771]
Hello Minio Team
I have been working with mino with asp.net core for few month. It worked very well with dotnet core. But when i try to implement mino with old mvc 5 project it gives me following error.

`Could not load file or assembly 'Minio' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`

**Comment by martijn00** [comment]
@ebozduman same as https://github.com/minio/minio-dotnet/issues/661 
Is fixed in the next version

**Comment by ebozduman** [comment]
@lujamaharjan 

@martijn00 is right. This is fixed in the coming release.

**Comment by ebozduman** [comment]
closing ...
