### ISSUE TITLE
Error (System.NullRefenceException) when connecting to AWS S3 with Minio Client

### ISSUE THREAD

**Issue by luanmm** [minio/minio-dotnet#788]
I'm using Minio Client to connect (in one of the environments) directly to an S3 instance (not a Minio server).

I'm using a Service Account (in my deployment/pod) to authenticate using IAM provider.

There is an error [in this line](https://github.com/minio/minio-dotnet/blob/5.0.0/Minio/Credentials/IAMAWSProvider.cs#L85). The logic seems to be wrong: is possible to see that `url` variable is getting its value from `CustomEndPoint` and in line 86 there is a test `url is null`, but if it can be null (which is my scenario), in the line 85 the variable couldn't be assigned to `url.Authority` (this is what throws the System.NullReferenceException).

**Comment by martijn00** [comment]
@luanmm @ebozduman this can be closed now.
