### ISSUE TITLE
ObjectStat.ObjectLockRetainUntilDate contains wrong value

### ISSUE THREAD

**Issue by ante-maric** [minio/minio-dotnet#808]
I believe there is bug in this code here:

```
case "x-amz-object-lock-retain-until-date":
                    var lockUntilDate = paramValue;
                    if (!string.IsNullOrWhiteSpace(lockUntilDate))
                        objInfo.ObjectLockRetainUntilDate = DateTime.SpecifyKind(
                            DateTime.Parse(lockUntilDate, CultureInfo.CurrentCulture),
                            DateTimeKind.Utc);
```

DateTime.Parse will convert lockUntilDate to local time. Then that local time changes kind to Utc. So, if your time zone is +2h what you will get back is 2h more than you set.

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by ante-maric** [comment]
> Can you make a PR to fix this?

I'll try to do it this week. There might be some other places where DateTime.Parse is being used, I'll check those too.

**Comment by ebozduman** [comment]
@ante-maric,

Could you test your scenario with #811 fix?
