### ISSUE TITLE
BucketExistsAsync not working

### ISSUE THREAD

**Issue by satishviswanathan** [minio/minio-dotnet#837]
I'm new to Minio and trying to get a sample file upload which works with play.min.io. However it fails in local environment with Minio running in docker instance.

Dotnet Version : 7
minio-dotnet version : 5.0.0
Running Minio locally using the docker compose

version: "3.4"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio_data:

**MiniClient implementation**

  using var minio = new MinioClient()
                .WithEndpoint("127.0.0.1", 9000)
                .WithCredentials("minioadmin", "minioadmin")
                .WithSSL(false)
                .Build();
 var bucketName = "SampleFolder";
 var location = "us-east-1";
var bktExistArgs = new BucketExistsArgs()
                .WithBucket(bucketName);
var found = await minio.BucketExistsAsync(bktExistArgs).ConfigureAwait(false);

That check always returns true even if the bucket doesn't exist.

Any help on this is appreciated !

**Comment by ebozduman** [comment]
@satishviswanathan 

I believe this issue is fixed in PR #844

Could you please test it and close it if it passes your test?

**Comment by ebozduman** [comment]
Closing as fixed.
Please reopen if you disagree.

**Comment by satishviswanathan** [comment]
@ebozduman Thank you for the fix.
