### ISSUE TITLE
Question about setting endpoint HTTPS schema

### ISSUE THREAD

**Issue by govorovvs** [minio/minio-dotnet#862]
Can someone explain to me why to set the https endpoint I have to specify environment variable ENABLE_HTTPS instead of simple setting `.WithEndpoint(new Uri("https://endpoint:port"))`? Thanks!

**Comment by govorovvs** [comment]
I have to communicate with two Minio servers - one on HTTPS endpoint, other - HTTP. How can I do that?

**Comment by ebozduman** [comment]
@govorovvs 

We follow Amazon s3 standard and this is the way endpoint is defined in s3.

You don't have to depend on the `ENABLE_HTTPS` env var. You can set the schema with `.WithSSL(bool secure)` for each Minio client, like:

```
isSecure1 = true;
var minioClient1 = new MinioClient()
            .WithEndpoint(endPoint1, port1)
            .WithCredentials(accessKey1, secretKey1)
            .WithSSL(isSecure1)
            .Build();
isSecure2 = false;
var minioClient2 = new MinioClient()
            .WithEndpoint(endPoint2, port2)
            .WithCredentials(accessKey2, secretKey2)
            .WithSSL(isSecure2)
            .Build();

Closing the issue as there is nothing to fix here. 
Please reopen it if you disagree.

**Comment by ebozduman** [comment]
Sorry! I reopened by mistake.
