### ISSUE TITLE
Broken AddMinio(...) method: Endpoint turns back to default

### ISSUE THREAD

**Issue by picolino** [minio/minio-dotnet#873]
I connect Minio sdk in my services this way:

```csharp
services.AddMinio(o =>
            {
                o.WithEndpoint("my.s3.com")
                    .WithCredentials(
                        Environment.GetEnvironmentVariable(s3AccessKeyEnv),
                        Environment.GetEnvironmentVariable(s3SecretKeyEnv)
                    );
            },
            ServiceLifetime.Scoped
        );
```

But when I try to use API through IMinioClient I have 'play.min.io' as an endpoint.

A little dig inside shows that in this code line we should also pass `configureClient`.
https://github.com/minio/minio-dotnet/blob/master/Minio/ServiceCollectionExtensions.cs#L47

And here Endpoint goes back to 'play.min.io':
https://github.com/minio/minio-dotnet/blob/master/Minio/MinioClientFactory.cs#L45

UPD: Minio version: 6.0.0

**Comment by picolino** [comment]
Workaround is pretty simple, we need to call `Build()` inside action, like that:
```
services.AddMinio(o =>
            {
                o.WithEndpoint("my.s3.com")
                    .WithCredentials(
                        Environment.GetEnvironmentVariable(s3AccessKeyEnv),
                        Environment.GetEnvironmentVariable(s3SecretKeyEnv)
                    )
                    .Build(); // Add this line to workaround this issue
            },
            ServiceLifetime.Scoped
        );
```

**Comment by ebozduman** [comment]
@picolino ,

Calling `.Build()` is not a workaround here, it is a requirement. That is, whenever you define  arguments to be fed to its function call, the `.Withxxxx()` calls are required to be followed by the `.Build()` function call at the end as the last call to manipulate and process the arguments data.
So, it works as expected, hence there is NO issue here.
Closed.

**Comment by Lightfire228** [comment]
If this works as expected, then you might want to update the documentation

per the [Readme](https://github.com/minio/minio-dotnet/blob/3cb2681938a3424c6a8654f8505ee5414bc90aff/README.md?plain=1#L35-L38)
```cs
        // Add Minio using the custom endpoint and configure additional settings for default MinioClient initialization
        builder.Services.AddMinio(configureClient => configureClient
            .WithEndpoint(endpoint)
            .WithCredentials(accessKey, secretKey));
```

**Comment by completej** [comment]
> @picolino ,
> 
> Calling `.Build()` is not a workaround here, it is a requirement. That is, whenever you define arguments to be fed to its function call, the `.Withxxxx()` calls are required to be followed by the `.Build()` function call at the end as the last call to manipulate and process the arguments data. So, it works as expected, hence there is NO issue here. Closed.

One caveat to this.  The .WithCredentials(accessKey, secretKey)) actually works without calling .Build(), which might have confused the issue.  When refactoring this out to a separate class for keeping Program clean, another example could be

```c#
        // Add Minio using the custom endpoint and configure additional settings for default MinioClient initialization
        services.AddMinio(configureClient => configureClient
            .WithEndpoint(config["APIs:Minio:Endpoint"])
            .WithCredentials(config["APIs:Minio:AccessKey"], config["APIs:Minio:SecretKey"])
            .WithSSL(true)
            .Build());
```

**Comment by ebozduman** [comment]
@completej,

Good point!
We'll look into it.
Thank you for the follow up.

**Comment by ebozduman** [comment]
Clarification: Although `Build()` is required and it is a documentation issue, there is still a bug and inconsistencies among the 3 overloads of WithEndpoint() method.
The PR#844 addresses these issues, and it is currently in the code review process. It'll be merged soon.
This issue still can stay closed though as it is also a duplicate of issue #887 which will be held open to track the issue and the verification of its fix.
