### ISSUE TITLE
Client .WithEndpoint() configuration

### ISSUE THREAD

**Issue by yermakovsergey** [minio/minio-dotnet#887]
I've got an asp.net project with minio driver version 5.0, everithin was fine.
Today tried to install latest 6.0 driver version and use AddMinio() instead of my old AddSingleton<IMinioClient, MinioClient>.
After modifications my service can't connect to minio.
I'm using AddMinio(configureClient => configureClient.WithEndpoint(connectionString).WithCredentials(AccessKey, SecretKey)
In log i got Minio.Exceptions.AccessDeniedException.
In debug mode I see that MinioClient BaseUrl is "play.min.io" instead of my url from connectionString.
![Screenshot minio endpoint](https://github.com/minio/minio-dotnet/assets/34538969/3f5efc59-6e7f-4ad6-aced-b898970d01a6)

**Comment by jonnyruffles** [comment]
Hi,

I think there's something seriously broken in version 6.0.0 of the Minio package.

Firstly, it looks like defining `.WithSSL(false)` simply does nothing. You only check if it's true, and if so, set secure to true (what if I want it to be false):
![image](https://github.com/minio/minio-dotnet/assets/136707592/589deb43-c0c5-42a9-b266-fe23c2f57143)

Secondly, you shouldn't be depending on the `USE_HTTPS` environment variable, it should be relying on the config object (whats the point in the UseSSL fluent method):
![image](https://github.com/minio/minio-dotnet/assets/136707592/1141bf00-edb8-4bb4-baa2-0374d54c0d20)

Thirdly, there is some really strange behaviour with the BaseURL. This config:
![image](https://github.com/minio/minio-dotnet/assets/136707592/b551de1d-54b8-4d45-aeb4-24f41c25b8cc)

doesn't properly set the BaseURL:
![image](https://github.com/minio/minio-dotnet/assets/136707592/ada9603b-8ef4-447b-8a48-a4d0a284514c)

**Comment by completej** [comment]
We are also seeing the issue concerning WithEndpoint after a 5.0 to 6.0 upgrade.

**Comment by yermakovsergey** [comment]
Ok, now I see that it's a documentation problem, there is no .build() in current .Net quick start guide.

**Comment by yermakovsergey** [comment]
well maybe, I just thought that my issue was duplicating that one [https://github.com/minio/minio-dotnet/issues/873](url)

**Comment by ebozduman** [comment]
@yermakovsergey , @jonnyruffles , @completej , @picolino

I believe this issue is fixed in PR #844

Could you please test it and close this issue if it passes your test?

**Comment by AyratShigapov** [comment]
Hi. When fixed nuget package will be availiable?

**Comment by ebozduman** [comment]
@AyratShigapov 

Next nuget package date is yet TBD. I'll let you all know as soon as it is decided.

**Comment by ebozduman** [comment]
Closing as fixed.
Please reopen if you disagree.
