### ISSUE TITLE
Issue with WithEndpoint() not setting Config.Endpoint

### ISSUE THREAD

**Issue by Shidesu** [minio/minio-dotnet#907]
Currently the 6.0.0 release has an issue with the WithEndpoint extension method not properly setting the client config Endpoint. Because of that, a minio client added through DI will always have the default endpoint.
It seems to have been fixed on the master branch.

When can we expect a release? Or at least a hotfix such as 6.0.1. The bug makes it impossible to use minio through DI.
<img width="722" alt="image" src="https://github.com/minio/minio-dotnet/assets/12526978/f206596d-5137-4183-8918-f3e0ee0312af">
Commit 3a38f1e

**Comment by SeanKilleen** [comment]
Thanks for adding this! I just happened to pick up the latest client and couldn't understand what I was doing wrong.

**Comment by ebozduman** [comment]
We've fixed this issue on the master branch, PR #844.
New nuget has not been created yet.
Closing...

**Comment by Shidesu** [comment]
> We've fixed this issue on the master branch, PR #844. New nuget has not been created yet. Closing...

Well, part of the question was: when can we expect a Nuget?

Apart from that, thanks for the work on the package, it's nice to use 👌
