### ISSUE TITLE
BucketExistsAsync does not handle exception properly

### ISSUE THREAD

**Issue by nwrox** [minio/minio-dotnet#945]
When testing a client configured with a fake endpoint, the method **BucketExistsAsync** still returns true, because there's not a check for other status codes or the exception isn't thrown here: https://github.com/minio/minio-dotnet/blob/9846edb923e676242203b087521667596889c225/Minio/ApiEndpoints/BucketOperations.cs#L84-L90
Is this correct?

**Comment by ebozduman** [comment]
@nwrox

I've tested and verified the fix, but please reopen if you find that the fix is not good in your env.
