### ISSUE TITLE
6.0.1 breaks StatObjectAsync behavior

### ISSUE THREAD

**Issue by Tim-Intigriti** [minio/minio-dotnet#947]
Previously on v6.0.0 using `.StatObjectAsync()` would result in an ´ObjectNotFoundException´ if the file was not found. Instead in 6.0.1 this results in an `ObjectStat` object with null/default values. 

Nothing was said about this in release notes so I suspect this isn't expected behavior?

**Comment by pangjianxin** [comment]
any update on this?i has the same issue

**Comment by ebozduman** [comment]
@pangjianxin

I am looking into it. This is a regression.

**Comment by ebozduman** [comment]
@Tim-Intigriti , @pangjianxin , @pgorka86 

I've tested and verified the fix, but please reopen if you find that the fix is not good in your env.
