### ISSUE TITLE
StatObjectAsync does not throw exception when object or bucket does not exist

### ISSUE THREAD

**Issue by MihaiDaniel** [minio/minio-dotnet#953]
As per specifications found here: 

- [3. Object operations](https://min.io/docs/minio/linux/developers/dotnet/API.html#object-operations) 

And in this tutorial 

- [How to Download MinIO Objects with .Net ](https://www.youtube.com/watch?v=_cd5bMKWmLY)

When calling `StatObjectAsync `the method should throw an exception if the object is not found. But instead this seems to return an `ObjectStat ` with default values instead.

I don't know if this is intended or not. I have not done anything special just installed it locally on windows 10, ran it and connected using a .NET 8 client. In the example below I just check the ETag if it's null or not, but I'm not sure if this is the best approach. 

```c#
using IMinioClient minioClient = _minioClientFactory.CreateClient();
minioClient.WithSSL(false);

StatObjectArgs statObjectArgs = new StatObjectArgs()
	.WithBucket("notexists")
	.WithObject("randomStuff123456789");

ObjectStat objectStat = await minioClient.StatObjectAsync(statObjectArgs);
if (objectStat.ETag == null)	
{
	return NotFound(false);
}
return Ok(true);
``` 

Thanks

**Comment by SamirWell** [comment]
I meet it as well  o(╥﹏╥)o

**Comment by ebozduman** [comment]
working on this...

**Comment by ebozduman** [comment]
@MihaiDaniel , @pangjianxin , @SamirWell 

I've tested and verified the fix, but please reopen the PR if the fix does not work in your scenario.

**Comment by rekarpcpro** [comment]
I think exception handling needs a review. 

my code:

`bool exists = await minioClient.BucketExistsAsync(new BucketExistsArgs().WithBucket(bucketName));
`

I will get `true` even if the minio container be down and not be accessible by any mean 🙄
