### ISSUE TITLE
has anyone tried this on the Dotnet docker image yet ?

### ISSUE THREAD

**Issue by joeblew99** [minio/minio-dotnet#98]
this is now at a point where it makes sense i think..

**Comment by harshavardhana** [comment]
> this is now at a point where it makes sense i think..

@joeblew99 we haven't tried this on docker yet, - this library is a work in progress for the time being. Is there anything specific you think that needs to be done for this library to work on docker?

**Comment by joeblew99** [comment]
Don't know - never tried it, and won't bother unless it's more than a sip, or at least is getting a CI where its tested.

**Comment by joeblew99** [comment]
Don't know - never tried it, and won't bother unless it's more than a sip, or at least is getting a CI where its tested.

**Comment by joeblew99** [comment]
Will leave it open as other might spot this who are using it

**Comment by harshavardhana** [comment]
Closing this as stale issue, we will re-open if this becomes an issue.
